<?php
if ($browserlang == "ko") {
	$rpi = "파이(Pi) 보드";
	$rpi_name = "Orange Pi 또는 Raspberry Pi";

	$text['VPN 접속 방법'] = 'VPN 접속 방법';
	$text[$brand_name.'은 PC와 모바일 거의 모든 기기에서 접속 가능합니다. 아래에서 접속하려는 기기를 선택해 접속방법을 확인하세요.'] = $brand_name.'은 PC와 모바일 거의 모든 기기에서 접속 가능합니다. 아래에서 접속하려는 기기를 선택해 접속방법을 확인하세요.';
	$text['Windows 10(8.1)에서 접속하기 (Windows 버전을 모르겠다면 여기를 선택하세요.)'] = 'Windows 10(8.1)에서 접속하기 (Windows 버전을 모르겠다면 여기를 선택하세요.)';
	$text['Windows 7에서 접속하기'] = 'Windows 7에서 접속하기';
	$text['Windows XP에서 접속하기'] = 'Windows XP에서 접속하기';
	$text['Android(안드로이드)에서 접속하기 (핸드폰, 테블릿)'] = 'Android(안드로이드)에서 접속하기 (핸드폰, 테블릿)';
	$text['iOS(iPhone, iPad)에서 접속하기 (아이폰, 아이패드)'] = 'iOS(iPhone, iPad)에서 접속하기 (아이폰, 아이패드)';
	$text['MAC OS에서 접속하기 (맥북, 아이팩)'] = 'MAC OS에서 접속하기 (맥북, 아이팩)';
	$text['Android TV(안드로이드TV)에서 접속하기 (구글TV, 크롬캐스트 with 구글TV, 미박스, Mi TV 스틱 등)'] = 'Android TV(안드로이드TV)에서 접속하기 (구글TV, 크롬캐스트 with 구글TV, 미박스, Mi TV 스틱 등)';
	$text[$rpi.'를 VPN 접속 공유기로 사용'] = $rpi.'를 VPN 접속 공유기로 사용';
	$text['중국에서 VPN 접속 후에도 구글이나 유투브가 열리지 않거나, VPN 접속이 가능하지않는 기기(스마트TV, 크롬캐스트, 구글TV)에서는 '.$rpi.'를 이용해 보세요. 한개의 VPN 접속 아이디로 두개의 디바이스에서 동시 접속이 가능한 방식입니다.'] = '중국에서 VPN 접속 후에도 구글이나 유투브가 열리지 않거나, VPN 접속이 가능하지않는 기기(스마트TV, 크롬캐스트, 구글TV)에서는 '.$rpi.'를 이용해 보세요. 한개의 VPN 접속 아이디로 두개의 디바이스에서 동시 접속이 가능한 방식입니다.';
	$text[$rpi.'를 VPN 접속 장비로 사용'] = $rpi.'를 VPN 접속 장비로 사용';
	$text[$rpi.$rpi_name.'라는 저렴한 초소형 컴퓨터를 VPN 접속 중개장비로 사용합니다.'] = $rpi.$rpi_name.'라는 저렴한 초소형 컴퓨터를 VPN 접속 중개장비로 사용합니다.';
	$text['모바일기기나 컴퓨터에서 VPN 접속이 어렵거나 번거로운 경우,'] = '모바일기기나 컴퓨터에서 VPN 접속이 어렵거나 번거로운 경우,';
	$text['중국과 같이 방화벽으로 다른 방식의 VPN 접속이 차단되거나,'] = '중국과 같이 방화벽으로 다른 방식의 VPN 접속이 차단되거나,';
	$text['VPN 접속 후에도 구글이나 유투브가 열리지 않는 곳에서 사용합니다.'] = 'VPN 접속 후에도 구글이나 유투브가 열리지 않는 곳에서 사용합니다.';
	$text['한개의 VPN 접속 아이디로 핸드폰과 노트북 두대를 동시에 사용할 수 있는 방식입니다.'] = '한개의 VPN 접속 아이디로 핸드폰과 노트북 두대를 동시에 사용할 수 있는 방식입니다.';
	$text[$rpi.'가 마치 VPN 공유기처럼 이용되며, 모바일기기나 컴퓨터는 별도 VPN 연결없이 '.$rpi.'로 WiFi 연결만하면 VPN IP를 사용하게 됩니다.'] = $rpi.'가 마치 VPN 공유기처럼 이용되며, 모바일기기나 컴퓨터는 별도 VPN 연결없이 '.$rpi.'로 WiFi 연결만하면 VPN IP를 사용하게 됩니다.';
	$text['자세한 방법 보러가기'] = '자세한 방법 보러가기';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등), 안드로이드 에뮬레이터에서 접속'] = '앱플레이어(블루스텍,녹스,LD,미뮤 등), 안드로이드 에뮬레이터에서 접속';
	$text['앱플레이어에서 VPN 접속을하면 앱플레이어마다 다른 아이피를 사용하여 게임을 할 수 있습니다.'] = '앱플레이어에서 VPN 접속을하면 앱플레이어마다 다른 아이피를 사용하여 게임을 할 수 있습니다.';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등)에서 접속 가능한 VPN 방식입니다.'] = '앱플레이어(블루스텍,녹스,LD,미뮤 등)에서 접속 가능한 VPN 방식입니다.';
	$text['IKEv2 또는 Openvpn 두 가지 방식의 접속이 가능합니다. 아래 두 가지 접속 방식 중 하나를 선택해 클릭하면 자세한 접속 방법을 확인할 수 있습니다.'] = 'IKEv2 또는 Openvpn 두 가지 방식의 접속이 가능합니다. 아래 두 가지 접속 방식 중 하나를 선택해 클릭하면 자세한 접속 방법을 확인할 수 있습니다.';
	$text['하나의 PC에서 여러 개의 앱플레이어를 사용하는 경우,'] = '하나의 PC에서 여러 개의 앱플레이어를 사용하는 경우,';
	$text['엡플레이어의 네트워크 설정에서 브릿지(DHCP)모드를 활성화하여 접속하면 더 안정적으로 사용할 수 있습니다.'] = '엡플레이어의 네트워크 설정에서 브릿지(DHCP)모드를 활성화하여 접속하면 더 안정적으로 사용할 수 있습니다.';
	$text['IKEv2 방식'] = 'IKEv2 방식';
	$text['앱플레이어에서 가장 안정적인 VPN 접속 방법입니다.'] = '앱플레이어에서 가장 안정적인 VPN 접속 방법입니다.';
	$text['OpenVPN 방식'] = 'OpenVPN 방식';
	$text['IKEv2 접속이 가능하지 않다면 이 방식을 이용하세요.'] = 'IKEv2 접속이 가능하지 않다면 이 방식을 이용하세요.';
	$text['중국에서 사용한다면, Openvpn 접속은 가능하지 않습니다. IKEv2 방식을 이용하세요.'] = '중국에서 사용한다면, Openvpn 접속은 가능하지 않습니다. IKEv2 방식을 이용하세요.';

} elseif ($browserlang == "zh") {
	$rpi = "Pi小型单板计算机";
	$rpi_name = "Orange Pi或Raspberry Pi";

	$text['VPN 접속 방법'] = 'VPN连接方法';
	$text[$brand_name.'은 PC와 모바일 거의 모든 기기에서 접속 가능합니다. 아래에서 접속하려는 기기를 선택해 접속방법을 확인하세요.'] = '可以在电脑和手机几乎所有机器上连接。请选择下面要连接的机器，确认连接方法。';
	$text['Windows 10(8.1)에서 접속하기 (Windows 버전을 모르겠다면 여기를 선택하세요.)'] = '从Windows 10（8.1）连接（如果不知道Windows版本，请选择这里。）';
	$text['Windows 7에서 접속하기'] = '从Windows 7连接';
	$text['Windows XP에서 접속하기'] = '从Windows XP连接';
	$text['Android(안드로이드)에서 접속하기 (핸드폰, 테블릿)'] = '从Android连接';
	$text['iOS(iPhone, iPad)에서 접속하기 (아이폰, 아이패드)'] = '从iPhone和iPad连接';
	$text['MAC OS에서 접속하기 (맥북, 아이팩)'] = '从MAC连接';
	$text['Android TV(안드로이드TV)에서 접속하기 (구글TV, 크롬캐스트 with 구글TV, 미박스, Mi TV 스틱 등)'] = '从AndroidTV连接';
	$text[$rpi.'를 VPN 접속 공유기로 사용'] = '使用'.$rpi.'作为VPN路由器';
	$text['중국에서 VPN 접속 후에도 구글이나 유투브가 열리지 않거나, VPN 접속이 가능하지않는 기기(스마트TV, 크롬캐스트, 구글TV)에서는 '.$rpi.'를 이용해 보세요. 한개의 VPN 접속 아이디로 두개의 디바이스에서 동시 접속이 가능한 방식입니다.'] = '尝试将'.$rpi.'用于即使在中国建立VPN连接后仍无法打开Goog​​le或YouTube或无法访问VPN的设备（智能电视，Chromecast，Google TV）。 这种方法允许同时使用一个VPN连接ID的两台设备进行访问';
	$text[$rpi.'를 VPN 접속 장비로 사용'] = '使用'.$rpi.'作为VPN路由器';
	$text[$rpi.$rpi_name.'라는 저렴한 초소형 컴퓨터를 VPN 접속 중개장비로 사용합니다.'] = '';
	$text['모바일기기나 컴퓨터에서 VPN 접속이 어렵거나 번거로운 경우,'] = '在移动设备或电脑上连接VPN困难或麻烦时，';
	$text['중국과 같이 방화벽으로 다른 방식의 VPN 접속이 차단되거나,'] = '像中国一样，通过防火墙切断其他方式的VPN连接，';
	$text['VPN 접속 후에도 구글이나 유투브가 열리지 않는 곳에서 사용합니다.'] = 'VPN连接后也在谷歌或YouTube不打开的地方使用。';
	$text['한개의 VPN 접속 아이디로 핸드폰과 노트북 두대를 동시에 사용할 수 있는 방식입니다.'] = '一个VPN连接ID可以同时使用手机和笔记本电脑。';
	$text[$rpi.'가 마치 VPN 공유기처럼 이용되며, 모바일기기나 컴퓨터는 별도 VPN 연결없이 '.$rpi.'로 WiFi 연결만하면 VPN IP를 사용하게 됩니다.'] = '';
	$text['자세한 방법 보러가기'] = '查看详细方法';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등), 안드로이드 에뮬레이터에서 접속'] = '通过Android Emulator连接手机游戏。';
	$text['앱플레이어에서 VPN 접속을하면 앱플레이어마다 다른 아이피를 사용하여 게임을 할 수 있습니다.'] = '您可以为每个Android模拟器使用不同的IP来玩游戏。';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등)에서 접속 가능한 VPN 방식입니다.'] = '这是可以从Android模拟器访问的VPN方法。';
	$text['IKEv2 또는 Openvpn 두 가지 방식의 접속이 가능합니다. 아래 두 가지 접속 방식 중 하나를 선택해 클릭하면 자세한 접속 방법을 확인할 수 있습니다.'] = '可以使用IKEv2方法进行VPN连接。';
	$text['하나의 PC에서 여러 개의 앱플레이어를 사용하는 경우,'] = '在一个PC上使用多个Android Emulator时，';
	$text['엡플레이어의 네트워크 설정에서 브릿지(DHCP)모드를 활성화하여 접속하면 더 안정적으로 사용할 수 있습니다.'] = '您可以通过在Android Emulator网络设置中激活网桥（DHCP）模式并进行连接来更稳定地使用它。';
	$text['IKEv2 방식'] = 'IKEv2 VPN';
	$text['앱플레이어에서 가장 안정적인 VPN 접속 방법입니다.'] = '这是Android仿真器中最稳定的VPN连接方法。';
	$text['OpenVPN 방식'] = '';
	$text['IKEv2 접속이 가능하지 않다면 이 방식을 이용하세요.'] = '';
	$text['중국에서 사용한다면, Openvpn 접속은 가능하지 않습니다. IKEv2 방식을 이용하세요.'] = '';

} else {  //en
	$rpi = "Pi Small Single-board Computer";
	$rpi_name = "Orange Pi or Raspberry Pi";

	$text['VPN 접속 방법'] = 'VPN connection method';
	$text[$brand_name.'은 PC와 모바일 거의 모든 기기에서 접속 가능합니다. 아래에서 접속하려는 기기를 선택해 접속방법을 확인하세요.'] = $brand_name.' can be connected from almost any PC and mobile device. Select the device you want to connect to below and check the connection method.';
	$text['Windows 10(8.1)에서 접속하기 (Windows 버전을 모르겠다면 여기를 선택하세요.)'] = 'Connecting from Windows 10(8.1) (If you are not sure of your Windows version, please select here.)';
	$text['Windows 7에서 접속하기'] = 'Connecting from Windows 7';
	$text['Windows XP에서 접속하기'] = 'Connecting from Windows XP';
	$text['Android(안드로이드)에서 접속하기 (핸드폰, 테블릿)'] = 'Connecting from Android';
	$text['iOS(iPhone, iPad)에서 접속하기 (아이폰, 아이패드)'] = 'Connecting from iOS(iPhone and IPad)';
	$text['MAC OS에서 접속하기 (맥북, 아이팩)'] = 'Connecting from MAC';
	$text['Android TV(안드로이드TV)에서 접속하기 (구글TV, 크롬캐스트 with 구글TV, 미박스, Mi TV 스틱 등)'] = 'Connecting from Android TV';
	$text[$rpi.'를 VPN 접속 공유기로 사용'] = 'Using '.$rpi.' as VPN router.';
	$text['중국에서 VPN 접속 후에도 구글이나 유투브가 열리지 않거나, VPN 접속이 가능하지않는 기기(스마트TV, 크롬캐스트, 구글TV)에서는 '.$rpi.'를 이용해 보세요. 한개의 VPN 접속 아이디로 두개의 디바이스에서 동시 접속이 가능한 방식입니다.'] = 'For devices that do not have VPN access (Smart TV, Chromecast, Google TV), try using '.$rpi.'. This is a method that allows simultaneous access from two devices with one VPN connection ID.';
	$text[$rpi.'를 VPN 접속 장비로 사용'] = 'Using '.$rpi.' as VPN router.';
	$text[$rpi.$rpi_name.'라는 저렴한 초소형 컴퓨터를 VPN 접속 중개장비로 사용합니다.'] = '';
	$text['모바일기기나 컴퓨터에서 VPN 접속이 어렵거나 번거로운 경우,'] = 'If VPN access is difficult or cumbersome from a mobile device or computer,';
	$text['중국과 같이 방화벽으로 다른 방식의 VPN 접속이 차단되거나,'] = 'or if other VPN access is blocked by a firewall like in China,';
	$text['VPN 접속 후에도 구글이나 유투브가 열리지 않는 곳에서 사용합니다.'] = 'you can use it.';
	$text['한개의 VPN 접속 아이디로 핸드폰과 노트북 두대를 동시에 사용할 수 있는 방식입니다.'] = 'With one VPN connection ID, you can use two mobile phones and laptops at the same time.';
	$text[$rpi.'가 마치 VPN 공유기처럼 이용되며, 모바일기기나 컴퓨터는 별도 VPN 연결없이 '.$rpi.'로 WiFi 연결만하면 VPN IP를 사용하게 됩니다.'] = '';
	$text['자세한 방법 보러가기'] = 'Go to see detailed instructions.';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등), 안드로이드 에뮬레이터에서 접속'] = 'Connecting from Android Emulator for mobile games.';
	$text['앱플레이어에서 VPN 접속을하면 앱플레이어마다 다른 아이피를 사용하여 게임을 할 수 있습니다.'] = 'You can play games using different IPs for each Android emulator.';
	$text['앱플레이어(블루스텍,녹스,LD,미뮤 등)에서 접속 가능한 VPN 방식입니다.'] = 'This is a VPN method that can be connected from the Android Emulator.';
	$text['IKEv2 또는 Openvpn 두 가지 방식의 접속이 가능합니다. 아래 두 가지 접속 방식 중 하나를 선택해 클릭하면 자세한 접속 방법을 확인할 수 있습니다.'] = 'There are two types of access available: IKEv2 or Openvpn. You can check the detailed connection method by selecting one of the two connection methods below and clicking on it.';
	$text['하나의 PC에서 여러 개의 앱플레이어를 사용하는 경우,'] = 'When using multiple Android Emulators on one PC,';
	$text['엡플레이어의 네트워크 설정에서 브릿지(DHCP)모드를 활성화하여 접속하면 더 안정적으로 사용할 수 있습니다.'] = 'you can use it more stably by activating Bridge (DHCP) mode in the Android Emulator network settings.';
	$text['IKEv2 방식'] = 'IKEv2 VPN';
	$text['앱플레이어에서 가장 안정적인 VPN 접속 방법입니다.'] = 'This is the most stable VPN connection method in Android Emulator.';
	$text['OpenVPN 방식'] = 'OpenVPN';
	$text['IKEv2 접속이 가능하지 않다면 이 방식을 이용하세요.'] = 'If IKEv2 access is not available, use this method.';
	$text['중국에서 사용한다면, Openvpn 접속은 가능하지 않습니다. IKEv2 방식을 이용하세요.'] = '';


}

?>