<?php
if ($browserlang == "ko") {
	$text['VPN 접속 현황'] = 'VPN 접속 현황';
	$text['현재 VPN 접속 중인 아이디 리스트 입니다. "끊기" 버튼으로 접속을 강제 종료할 수 있지만, 비밀 번호를 변경하지 않았다면 바로 다시 접속될 수 있습니다.'] = '현재 VPN 접속 중인 아이디 리스트 입니다. "끊기" 버튼으로 접속을 강제 종료할 수 있지만, 비밀 번호를 변경하지 않았다면 바로 다시 접속될 수 있습니다.';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = '서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.';
	$text['아이디'] = '아이디';
	$text['접속시간'] = '접속시간';
	$text['할당 IP'] = '할당 IP';
	$text['Home IP'] = 'Home IP';
	$text['서버'] = '서버';
	$text['Type'] = 'Type';
	$text['연결끊기'] = '연결끊기';
	$text['끊기'] = '끊기';
	$text['강제로 연결을 끊습니다.'] = '강제로 연결을 끊습니다.';
	$text['VPN에 접속되어 있는 계정이 없습니다.'] = 'VPN에 접속되어 있는 계정이 없습니다.';
	$text['현재 접속되어 있는 계정을 확인하려면 클릭하세요'] = '현재 접속되어 있는 계정을 확인하려면 클릭하세요';
	$text['접속 현황 다시 확인'] = '접속 현황 다시 확인';
	$text['돌아가기'] = '돌아가기';

} elseif ($browserlang == "zh") {
	$text['VPN 접속 현황'] = 'VPN连接现状';
	$text['현재 VPN 접속 중인 아이디 리스트 입니다. "끊기" 버튼으로 접속을 강제 종료할 수 있지만, 비밀 번호를 변경하지 않았다면 바로 다시 접속될 수 있습니다.'] = '现在正在连接VPN的ID列表。"断开"按钮可以强制关闭连接，但如果没有更改密码，可以立即连接';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = '服务器连接失败。对不起。稍后再做一次吧';
	$text['아이디'] = 'ID';
	$text['접속시간'] = '连接时间';
	$text['할당 IP'] = '被分配的IP';
	$text['Home IP'] = 'Home IP';
	$text['서버'] = 'Server';
	$text['Type'] = 'Type';
	$text['연결끊기'] = '断开';
	$text['끊기'] = '断开';
	$text['강제로 연결을 끊습니다.'] = '强制断开连接。';
	$text['VPN에 접속되어 있는 계정이 없습니다.'] = '没有连接VPN的ID';
	$text['현재 접속되어 있는 계정을 확인하려면 클릭하세요'] = '点击查看当前登录的ID';
	$text['접속 현황 다시 확인'] = '再次确认连接情况';
	$text['돌아가기'] = '返回';

} else {  //en
	$text['VPN 접속 현황'] = 'Current VPN Connection Status';
	$text['현재 VPN 접속 중인 아이디 리스트 입니다. "끊기" 버튼으로 접속을 강제 종료할 수 있지만, 비밀 번호를 변경하지 않았다면 바로 다시 접속될 수 있습니다.'] = 'This is a list of IDs currently connected to the VPN. The connection can be forcibly terminated with the "Disconnect" button, but if the password of the ID has not been changed, the ID can be reconnected immediately.';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = 'Failed to connect to the server. Sorry. Please try again after a while.';
	$text['아이디'] = 'ID';
	$text['접속시간'] = '접속시간';
	$text['할당 IP'] = '할당 IP';
	$text['Home IP'] = 'Home IP';
	$text['서버'] = 'Server';
	$text['Type'] = 'Type';
	$text['연결끊기'] = 'Disconnect';
	$text['끊기'] = 'Disconnect';
	$text['강제로 연결을 끊습니다.'] = 'Forcibly disconnect.';
	$text['VPN에 접속되어 있는 계정이 없습니다.'] = 'There is no ID connected to the VPN.';
	$text['현재 접속되어 있는 계정을 확인하려면 클릭하세요'] = 'Click to check the ID you are currently connected to.';
	$text['접속 현황 다시 확인'] = 'Check the connection status again';
	$text['돌아가기'] = 'Go back';

}

?>