<?php
if ($browserlang == "en") {
	$text['상단으로 이동'] = 'Go to the top';

	//win7
	$text['Windows 7 VPN 접속 방법'] = 'How to connect to VPN in Windows 7';
	$text['"제어판 ->  프로그램"에서 접속 프로그램을 삭제할 수 있습니다.'] = 'You can delete the program from Control Panel -> Programs.';
	$text['접속하기'] = 'Connect';

	//win7 IKEv2M
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] ='Put the mouse pointer over the network (or WiFi) connection tray icon, click "right mouse button" and select "Open Network and Sharing Center".';
	$text['"네트워크 설정 변경" 아래의 "새 연결 또는 네트워크 설정"을 클릭합니다.'] = 'Click "Set up a new connection or network" under "Change your networking settings".';
	$text['"회사에 연결"을 선택하고 "다음"을 클릭합니다.'] = 'Select "Connect to a workplace" and click "Next".';
	$text['"아니요, 새 연결을 만듭니다."를 선택하고 "다음"을 클릭합니다.'] = 'Select "No, create a new connection" and click "Next".';
	$text['"내 인터넷 연결 사용(VPN)"을 클릭합니다.'] = 'Click "Use my Internet connection (VPN)".';
	$text['"인터넷 주소"에 아래 서버 주소 중 하나를 선택해 입력하고 "대상 이름"에 "'.$brand_name.'"를 입력하고, "지금 연결하지 않고 나중에 연결할 수 있도록 설정해 놓기만 함"을 선택해 활성화하고 "다음"을  클릭합니다.'] = 'Select and enter one of the server addresses below in "Internet address" enter "'.$brand_name.'" in "Destination name", select "Don\'t connect now, just set it up so I can connect later" to activate it and click "Next".';
	$text['서버주소'] = 'Server addresses';
	$text['사용자 이름과 암호에 "'.$vpnid.'"와(과) 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = 'Enter "'.$vpnid.'" and password for Username and Password and leave "Domain(optional)" blank.';
	$text['사용자 이름과 암호에 '.$account_url.'에서 생성한 아이디와 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = 'In Username and Password, enter the VPN connection ID and Password created in '.$account_url.' and leave "Domain(optional)" blank.';
	$text['"만들기"와 "닫기"를 차례로 클릭하여 내용을 저장하고 설정 창을 닫습니다.'] = 'Click "Create" and then "Close" to save the contents and close the settings window.';
	$text['"<strong>어댑터 설정 변경</strong>"을 클릭합니다.'] = 'Click "<strong>Change adapter options</strong>".';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = 'Put the mouse over '.$brand_name.' adapter, click <strong>Right</strong> button and select "<strong>Properties</strong>" from the the menu.';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = 'If the Properties window opens, select the "Networking" tab. Select "Internet Protocol Version 4(TCP/IPv4)" and click "Properties".';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = 'Click "<strong>Advanced</strong>" as shown, select "<strong>Use default gateway on remote network</strong>" to activate it and click OK a few times to save your changes.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 선택하면 나타나는 "연결" 버튼을 클릭하여 접속할 수 있습니다.'] = 'You can connect by clicking the network (or WiFi) connection tray icon and clicking the "Connect" button that appears if you select "'.$brand_name.'" icon as shown in the picture.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "IPany (연결됨)" 아이콘을 선택하면 나타나는 "연결 끊기" 버튼을 클릭합니다.'] = 'Click the network (or WiFi) connection tray icon and click the "Disconnect" button that appears if you select the "'.$brand_name.'" icon as shown in the picture.';
	$text['네트워크(또는 WiFi)연결 트레이 아이콘을 클릭합니다. "IPany"에 마우스를 올리고 마우스 오른쪽 버튼을 클릭한 후 "속성"을 클릭합니다.'] = 'Click the network (or WiFi) connection tray icon. Put the mouse over "'.$brand_name.'", click right button and click "Properties".';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = 'Enter the server address you want to change in "Host name or IP Address of destination" and click the "OK" button.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] = 'Put the mouse pointer over the network (or WiFi) connection tray icon, click "Right mouse button" and select "Open Network and Sharing Center".';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = 'Click "Change adapter options".';
	$text[$brand_name.'에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "삭제"를 선택합니다.'] = 'Put the mouse pointer on '.$brand_name.', click "Right mouse button" and select "Delete".';

	//win10 pptpm
	$text['<strong>PPTP VPN 접속 직접 설정 방법</strong>입니다.'] = 'This is <strong>PPTP VPN connection method directly</strong>.';
	$text['PPTP 접속 직접 설정하기'] = 'How to set up PPTP connection directly';
	$text['여기서는 직접 PPTP 접속을 설정하는 방법을 설명합니다.'] = 'This section explains how to set up direct PPTP connection.';
	$text['"PPTP(지점 간 터널링 포르토콜)" 선택'] = 'Select "Point to Point Tunneling Protocol(PPTP)"';
	$text['PPTP 접속이 가능한 서버는 아래와 같습니다.'] = 'Servers that can connect to PPTP are as follows.';

	//win10 pptp
	$text['<strong>PPTP VPN 접속 방법</strong>입니다.'] = 'This is <strong>PPTP VPN connection method</strong>.';
	$text['예전에 사용하던 VPN 방식입니다. 방화벽이나 일부 오래된 공유기를 사용는 환경에서는 접속이 가능하지 않을 수 있습니다(619 오류 발생)'] = 'This is the VPN method used in the past. Connection may not be possible in the environment where a firewall or some old router is used (Error 619).';
	$text['PPTP 방식은 접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "접속 설정 방법"을 확인하세요.'] = 'In PPTP method, you can connect with simple VPN connection setting of Windows itself without installing a connection program. If you do not want to install the program and want to set up the connection directly, click here to see "How to set up direct connection".';
	$text['VPN 방식을 "PPTP"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = 'You can connect by selecting "PPTP" as VPN method, selecting a connection server and clicking "Connect".';
	$text['공유기 문제나 방화벽으로 차단되어 있어 접속할 수 없는 경우입니다. 다른 VPN 방식으로 접속해야 합니다.'] = 'This connection error occurs by router problem firewall block. You need to connect with different VPN method.';


	//win10 IKEv2M
	$text['<strong>IKEv2 VPN 접속 직접 설정 방법</strong>입니다. 위 탭에서 다른 VPN 방식을 확인할 수 있습니다.'] = 'This is <strong>IKEv2 VPN conection method direclty</strong>. You can see the different VPN methods in the tab above.';
	$text['여기서는 직접 IKEv2 접속을 설정하는 방법을 설명합니다.'] = 'This section explains how to set up direct IKEv2 connection.';
	$text['직접 설정이 번거롭다면 통합 접속프로그램으로 간편하게 접속할 수 있습니다. 여기를 클릭해 프로그램 설치 방법을 확인하세요.'] = 'If the direct setting is inconvenient, you can easily connect VPN with the integrated connection program. Click here to see how to install the program.';
	$text['IKEv2 접속 직접 설정하기'] = 'How to set up IKEv2 connection directly';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 "네트워크 설정"을 클릭합니다.'] = 'Click the network (or WiFi) connection tray icon and click "Network & Internet settings".';
	$text['좌측 창에서 "VPN"을 선택하고 오른쪽 창에서 "VPN 연결 추가"를 클릭합니다.'] = 'Select "VPN" in the left side and click "Add a VPN Connection" in the right side.';
	$text['"VPN 연결 추가" 창이 열리면 아래와 같이 각 항목을 입력 또는 선택하고 "저장"을 클릭합니다.'] = 'If the "Add a VPN Connection" window opens, enter or select each item as shown below and click "Save".';
	$text['VPN 공급자'] = 'VPN provider';
	$text['"Windows(기본 제공)" 선택'] = 'Select "Windows(built-in)"';
	$text['연결 이름'] = 'Connection name';
	$text['"'.$brand_name.'" 입력'] = 'Enter "'.$brand_name.'" ';
	$text['서버 이름 또는 주소'] = 'Server name or address';
	$text['아래 서버 주소 중 하나를 선택해 입력'] = 'Select and enter one of the server addresses below';
	$text['VPN 종류'] = 'VPN type';
	$text['"IKEv2" 선택'] = 'Select "IKEv2"';
	$text['로그인 정보 입력'] = 'Type of sign-in info';
	$text['"사용자 이름 및 암호" 선택'] = 'Select "User name and password"';
	$text['사용자 이름(옵션)'] = 'User name(optional)';
	$text['"'.$vpnid.'"을(를) 입력합니다.'] = 'Enter "'.$vpnid.'".';
	$text[$account_url.'에서 생성한 아이디를 입력합니다.'] = 'Enter VPN connection ID created in '.$account_url.'.';
	$text['암호(옵션)'] = 'Password(optional)';
	$text['"'.$vpnid.'" 생성 시 같이 입력한 비밀번호를 입력합니다.'] = 'Enter the Password that input together on creation of "'.$vpnid.'".';
	$text[$account_url.'에서 생성한 아이디의 비밀번호를 입력합니다.'] = 'Enter the Password of the VPN connection ID created in '.$account_url.'.';
	$text['관련 설정의 "<strong>어댑터 옵션 변경</strong>"을 클릭합니다.'] ='Click "<strong>Change adapter options</strong>" of Related settings.';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = 'Put the mouse over '.$brand_name.' adapter, click "Right mouse button" and select "Properties" from the menu that appears.';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = 'If the Properties window opens, select the "Networking" tab. Select "Internet Protocol Version 4 (TCP/IPv4)" and click "Properties".';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = 'Click "<strong>Advanced</strong>" as shown, select "<strong>Use default gateway on remote network</strong>" to activate it and click OK a few times to save your changes.';
	$text['모든 설정이 끝났다면, VPN에 생성된 '.$brand_name.'를 선택하고 "연결"을 클릭하여 바로 접속할 수 있습니다.'] = 'If all settings are done, you can connect right away by selecting '.$brand_name.' created in the VPN and clicking "Connect".';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = 'If the connection is successful, you will use the Internet with the fixed IP selected in "Account Management".';
	$text['접속 끊기'] = 'Disconnection';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.' (연결됨)" 아이콘을 클릭합니다.'] = 'Click the network(or WiFi) connection tray icon and click the "'.$brand_name.' (Connected)" icon as shown.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.' 연결됨" 을 선택하고 "연결 끊기"를 클릭합니다.'] = 'If "Network & Internet" window opens, select "'.$brand_name.' Connected" and click "Disconnect".';
	$text['다시 접속하기'] = 'Reconnection';
	$text['접속 프로그램을 설치하거나 접속 설정을 만들었다면 언제든 아래의 방법으로 다시 접속할 수 있습니다.'] = 'If you have installed the connection program or done connection settings, you can connect again at any time as following method.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = 'Click the network(or WiFi) connection tray icon and click the "'.$brand_name.'" icon as shown.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "연결"을 클릭합니다.'] = 'If "Network & Internet" window opens, select "'.$brand_name.'" and click "Connect".';
	$text['전에 "암호 저장"을 선택했었다면 바로 접속됩니다.'] = 'If you have previously selected "Remember my sign-in info", Connection will be done immediately.';
	$text['전에 입력하지 않았었다면 접속 로그인 창이 열립니다. 사용자 이름과 암호를 입력하고 "확인"을 클릭하여 접속할 수 있습니다.'] = 'If you have not entered before, the Sign in window will be open. You can connect by inputting User name and Password and clicking "OK".';
	$text['접속 서버 변경 방법'] = 'How to change the connection server';
	$text[$brand_name.'는 다중 접속 서버를 제공합니다. 언제든 원한다면 자신이 사용 중인 인터넷과 잘 맞는 서버를 선택해 접속할 수 있습니다. 접속 서버를 변경하는 방법은 아래와 같습니다.'] = $brand_name.' provides multiple access servers. Whenever you want, you can select a server that fits your internet connection and access it. There is connection server change method as follows.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하고 "네트워크 및 공유 센터 열기"를 선택합니다.'] = 'Put the mouse pointer over the network (or WiFi) connection tray icon, click "right mouse button" and select "Open Network & Internet settings".';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = 'Click "Change adapter options".';
	$text['"'.$brand_name.'"에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하면 나타나는 메뉴 중 속성을 선택합니다.'] = 'Put the mouse pointer over "'.$brand_name.'", click "Right mouse button" and select "Properties".';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = 'Enter the server address you want to change in "Host name or IP Address of destination" and click the "OK" button.';
	$text['IKEv2 접속이 가능한 서버는 아래와 같습니다.'] = 'Servers that is available to IKEv2 connection are as follows.';
	$text['접속에 실패하면 접속 프로그램의 "연결 상태"에서 접속 실패 원인과 "오류 번호"를 확인할 수 있습니다.'] = 'If the connection fails, you can check the cause of the connection failure and the "Error code" in "Connection Status" of the connection program.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = 'Click the network(or WiFi) connection tray icon and click the "'.$brand_name.'" icon as shown.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "제거"를 클릭합니다.'] = 'If "Network & Internet" window opens, select "'.$brand_name.'" and click "Remove".';

	//OpenvpnS
	$text['<strong>OpenVPN 이중 암호화</strong> 접속 방법입니다. 중국에서 IKEv2 접속에 문제가 있다면 이 방법을 이용합니다. Stunnel이라는 암호화 터널을 미리 구성하여 그 터널을 통해 OpenVPN 접속이 가능하게 하는 방식입니다.'] = 'This is <strong>OpenVPN double encryption connection method</strong>. If you have trouble to connect to IKEv2 in China, use this method. This is a method that enables OpenVPN access through the tunnel by pre-configuring an encrypted tunnel called Stunnel.';
	$text['VPN 방식을 "OpenVPNSSL"로 선택합니다. OpenVPNSSL 접속을 위해서는 OpenVPN과 Stunnel 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = 'Select "OpenVPNSSL" as the VPN method. To connect to OpenVPNSSL, you need to install OpenVPN and Stunnel program. If it is not installed, it will be installed automatically.';

	//Openvpn
	$text['<strong>OpenVPN 접속 방법</strong>입니다. IKEv2 접속이 가능하지 않다면 이방법을 이용하세요. 하지만, 중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL(이중 암호화 방식)을 이용하세요.'] = 'This is <strong>OpenVPN connection method</strong>. If you cannot connect to IKEv2, use this method. However, OpenVPN access is not available in China. Instead, use OpenVPN SSL (double encryption).';
	$text['통합 접속 프로그램을 설치하지 않았다면, 아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = 'If you have not installed the integrated connection program, click the download button below to download the installation file.';
	$text['VPN 방식을 "OpenVPN"로 선택합니다. OpenVPN 접속을 위해서는 OpenVPN 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = 'Select the VPN method as "OpenVPN". To access OpenVPN, you need to install the OpenVPN program. If it is not installed, it will be installed automatically.';
	$text['프로그램 설치 시 디바이스 설치를 묻는 창이 뜨면 반드시 "Install"을 선택해야합니다.'] = 'When install the program, a window asking you to install the device appears, you must select "Install".';
	$text['접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = 'After selecting a connection server, you can connect by clicking "Connect".';
	$text['원인을 알수 없는 경우, OpenVPN GUI 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭한 후 "View Log"를 선택하면 메모장이 열리며 접속 로그를 확인할 수 있습니다.'] = 'If the cause is unknown, place the mouse pointer on the OpenVPN GUI tray icon, right-click, and select "View Log" to open the notepad and check the access log.';
	$text['접속 로그 내용에 따른 접속 실패 원인과 해결 방법입니다.'] = 'These are the causes and solutions for connection failure according to the contents of the connection log.';
	$text['(표)OpenVPN 오류 로그 - ipany.net'] = '(Table)OpenVPN Error log - '.$brand_name;
	$text['접속 로그 내용'] = 'Connection log contents';
	$text['접속 실패 원인 및 해결 방법'] = 'Connection failure causes and solutions';
	$text['AUTH: Received control message: AUTH_FAILED'] = 'AUTH: Received control message: AUTH_FAILED';
	$text['Username 이나 Password를 잘못 입력하거나, 만기일이 지나거나, 이미 다른 기기나 컴퓨터에서 접속되어 있는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. '.$account_url.'에서 계정 상태를 확인하세요.'] = 'This error occurs by incorrect username or incorrect password or expiry or reacces try while accessed. '.$brand_name.' doesn\'t provide duplicate connection with same account. You can check the status of your account in '.$account_url.'.';
	$text['RESOLVE: Cannot resolve host address: ipany...'] = 'RESOLVE: Cannot resolve host address: ipany...';
	$text['DNS 문제로 IPany VPN 서버를 찾지 못하는 경우입니다. 컴퓨터의 DNS 설정에서 DNS 서버 주소를 168.126.63.1로 변경해 주세요.'] = 'This error occurs by no '.$brand_name.' server found due to DNS problem. Change the DNS server addresses as 168.126.63.1 in your computer\'s DNS settings.';
	$text['All TAP-Win32 adapters on this system are currently in use'] = 'All TAP-Win32 adapters on this system are currently in use';
	$text['가상 드라이브가 이미 실행되고 있는 경우입니다. 컴퓨터를 재부팅하고 접속합니다.'] = 'Virtual drive running is already done. Reboot your computer and connect.';
	$text['"Unable to connect because your certificate is not yet valid. Check that your system time is correct" 라는 메세지가 뜨는 경우'] = 'In case of message display "Unable to connect because your certificate is not yet valid. Check that your system time is correct"';
	$text['사용자 컴퓨터의 현재 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간을 현재시간으로 조정한 후 접속합니다.'] = 'The current time in your computer is incorrect. Connect after adjusting the current time correctly in your computer.';
	$text['TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)'] = 'TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)';
	$text['사용자의 인터넷 연결 상태가 불안하거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다. 또 다른 이유는 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = 'This error occurs by unstable user’s internet connection, or bad connection status between user’s local internet and '.$brand_name.' line. If you are using router, turn it off for about 10 minutes and try again. Another reason is due to wrong time set in your computer. Adjust time setting correctly in your computer.';
	$text['TLS Error: Unroutable control packet received'] = 'TLS Error: Unroutable control packet received';
	$text['사용자의 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = 'It\'s wrong time setting in user\'s computer. Check time setting in your computer.';
	$text['UDP/TCP: connect to ipany... failed'] = 'UDP/TCP: connect to ipany... failed';
	$text['IPany VPN 서버로 접속할 수 없는 경우입니다. 인터넷이 연결되어 있지 않거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다.'] = 'This is connection impossible by '.$brand_name.' server. It occurs by no internet connection, or bad connection status between user’s local internet and '.$brand_name.' line. If you are using a router, turn it off for about 10 minutes, then turn it on and try again.';
	$text['TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds'] = 'TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds';
	$text['OpenVPN 이중 암호 방식 접속은 OpenVPN 접속 전에 Stunnel이 먼저 실행되어 있어야 합니다. Stunnel이 실행되어 있지 않아 발생하는 문제입니다. Stunnel를 먼저 실행하고 다시 접속합니다.'] = 'Stunnel must be running before OpenVPN access. This is occurred by inactivated Stunnel. Activate Stunnel first and connect again';
	$text['OpenVPN 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = 'If you don\'t even use OpenVPN program, you can uninstall it here.';
	$text['OpenVPN과 Stunnel 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = 'If you are don\'t use OpenVPN and Stunnel programs, you can also uninstall them here.';


	//win10
	$text['직접설정'] = 'Direct setting';
	$text['이중암호화'] = 'double encryption';
	$text['Windows 10 VPN 접속 방법'] = 'How to connect to VPN in Windows 10';
	$text['다른 디바이스 접속 방법 보러 가기'] = 'Go to see how to connect from other devices';
	$text['아래 방법으로 VPN 접속을 할 수 있습니다. 접속아이디에 "'.$vpnid.'"을(를) 사용하세요.'] = 'You can connect to the VPN as following way. Please use "'.$vpnid.'" for VPN connection ID.';
	$text['가장 많이 사용되는 <strong>IKEv2 VPN 접속 방법</strong>입니다.'] = 'This is the most commonly used IKEv2 VPN connection method.';
	$text['접속 프로그램 설치 및 접속'] = 'Connection program installation and connection';
	$text['아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = 'Click the button below to download the installation file.';
	$text['통합 접속프로그램 다운받기'] = 'Download the integrated connection program';
	$text['접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "직접 접속 설정 방법"을 확인하세요.'] = 'You can connect to VPN by simple VPN connection setting in Windows itself without installing the connection program. If you want to set up VPN connection without installing the connection program, click here.';
	$text['브라우저의 다운로드 관련 메세지가 나타나면 "저장"을 선택하여 다운로드한 설치파일을 저장합니다.'] = 'When the browser\'s download message appears, select "Save" to save the downloaded installation file.';
	$text['다운로드가 끝나고 "폴더 열기"을 선택하면 다운로드된 파일이 저장된 폴더가 열리게 됩니다.'] = 'When the download is finished, select "Open folder" to open the folder of downloaded file.';
	$text['zip 파일의 압축을 풀어주면 나오는 실행 파일을 더블 클릭하여 실행합니다.'] = 'After unzipping the zip file, double-click the exe file to run it.';
	$text['그림과 같이 "Windows PC 보호" 창이 열린다면 "추가 정보"를 클릭하면 "실행" 버튼이 보이게 됩니다. "실행" 버튼을 클릭합니다.'] = 'If the "Windows protected your PC" window appears as below, click "More info" and then click "Run anyway" button.';
	$text['그림과 같이 "사용자 계정 컨트롤" 창이 열린다면 "예"를 선택합니다.'] = 'If the "User Account Control" window appears as below, select "Yes".';
	$text['프로그램 설치를 마치고, 바탕화면 바로가기나 시작 메뉴에서 IPanyVPN을 클릭하여 프로그램을 실행합니다.'] = 'After installing the program, click IPanyVPN from the desktop shortcut or the Start menu to run the program.';
	$text['통합 접속 프로그램이 열리면,'] = 'When the integrated access program opens,';
	$text['접속아이디에 "'.$vpnid.'"을(를) 입력하고, 비밀번호를 입력하세요.'] = 'Enter "'.$vpnid.'" in Username and enter the password.';
	$text[$account_url.'에서 생성한 계정의 접속아이디와 비밀번호를 입력합니다.'] = 'enter the connection ID and password created in '.$account_url.'.';
	$text['VPN 방식을 "IKEv2"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = 'Select "IKEv2" as the VPN type and choose one of connection servers. And then you can connect to VPN by clicking "Connect" button.';
	$text['VPN 방식'] = 'VPN type';
	$text['IKEv2 접속에 문제가 있다면, Openvpn 접속 방식을 선택하세요. (중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL을 사용하세요.)'] = 'If you have trouble to connect to IKEv2, select Openvpn for VPN type. (OpenVPN is not available in China. Use OpenVPN SSL instead.)';
	$text['접속 서버'] = 'Connection server';
	$text['IPany는 다중 접속 서버를 제공합니다. 접속이 원할하지 않다면 다른 서버를 선택해 접속할 수 있습니다.'] = $brand_name.' provides multiple access servers. If there is a problem with the connection, you can select other server to connect.';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = 'If you succeed in connecting to VPN, you will use Internet with the Korea IP selected in Account Management.';
	$text['<span class="badge badge-danger">중국</span> 중국에서 접속 시 VPN 접속 후에도 구글 페이스북이 열리지 않는다면 DNS 서버 설정을 변경해야 합니다. 방법을 확인하려면 여기를 클릭하세요.'] = '<span class="badge badge-danger">China</span> In China, if website(ex : Google) or social media like Facebook, Instagram and etc. is not open even after VPN connection, you need to change the DNS server settings. Click here to see how.';
	$text[$osname.'에서 DNS 서버를 한국 DNS 서버로 변경하는 방법입니다.'] = 'This is how to change DNS server to Korean DNS server in '.$osname;
	$text['윈도우 데스크톱 화면의 오른쪽 아래의 네트워크 트레이 아이콘에 마우스를 올리고 마우스 오른 쪽 버튼을 클릭합니다. <strong>네트워크 및 공유 센터 열기</strong>를 선택합니다.'] = 'Put the mouse over the network tray icon in the lower right corner of the Windows desktop screen and click the right mouse button. Select <strong>Open Network & Internet settings</strong>.';
	$text['PC가 인터넷에 연결된 이더넷이나 WiFi의 연결을 클릭합니다.'] = 'Click the Ethernet or WiFi connection where your PC is connected to the Internet.';
	$text['속성을 클릭합니다.'] = 'Click Properties.';
	$text['인터넷 프로토콜 버전4(TCP/IPv4)를 더블 클릭합니다.'] = 'Double-click Internet Protocol Version 4 (TCP/IPv4).';
	$text['"다음 DNS 서버 주소 사용"을 선택하고 그림과 같이 DNS 서버 주소를 입력합니다.'] = 'Select "Use the following DNS server addresses" and enter the DNS server addresses as shown.';
	$text['"확인" 및 "닫기" 버튼을 연속으로 선택하여 변경 내용을 적용합니다.  PC를 재부팅 합니다.'] = 'Select the "OK" and "Close" buttons in succession to apply the changes. Reboot your PC.';
	$text['이 방법으로도 해결이되지 않는다면 <a href="connects_rpi_rpi.php">PI보드를 이용한 VPN 접속 방법</a>을 사용해야 합니다.'] = 'If this doesn\'t work, you should use <a href="connects_rpi_rpi.php">VPN connection method using the PI board.</a>';
	$text['접속 장애 확인'] = 'Connection failure check';
	$text['접속에 실패하면 접속 실패창이 뜨게됩니다. 여기서 접속 실패 원인을 확인할 수 있습니다.'] = 'If the connection fails, the connection failure window appears. Here you can check the cause of the connection failure.';
	$text['주요 "오류 번호"에 따른 접속 실패 원인과 해결 방법입니다.'] = 'Main causes and solutions of connection failure by each "error code" are as below.';
	$text['오류'] = 'Error';
	$text['원인 및 해결방법'] = 'Connection failure causes and solutions';
	$text['접속 계정의 사용자 이름, 비밀번호가 잘못되거나, 만기일이 지났거나, 이미 접속되어 있는데 다시 접속을 시도하는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. IPany.net 홈페이지의 "<a href="staticip.php">계정 관리</a>"에서 해당 계정 상태를 확인합니다.'] = 'This error occurs by incorrect username or incorrect password or expiry or reacces try while accessed. '.$brand_name.' doesn\'t provide duplicate connection with same account. You can check the status of your account in <a href="staticip.php">Account Management</a> of the '.$brand_name.' website.';
	$text['접속 서버를 찾지 못해 발생하는 오류입니다. 인터넷 연결이 되어있지 않은 경우, DNS 오류, 방화벽으로 차단된 경우입니다. DNS 오류의 경우는 컴퓨터의 DNS 서버 설정을 "168.126.63.1"로 변경하여 해결 할 수 있습니다. 방화벽으로 차단된 경우는 다른 VPN 방식으로 접속해야 합니다.'] = 'This error occurs by no access server found. It comes from no internet connection or DNS error or block by firewall. DNS errors can be solved by changing the DNS server IP in your computer or router as "168.126.63.1". If it is blocked by firewall, you can try other VPN type.';
	$text['오류87 "매개변수가 틀립니다."는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = 'Error 87 "The parameter is incorrect" is due to a problem with the Windows OS itself. The solution is explained in <a href="howto.php">Troubleshooting</a>.';
	$text['오류809는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = 'Error 809 is due to a problem with the Windows OS itself. The solution is explained in <a href="howto.php">Troubleshooting</a>.';
	$text['접속기 삭제'] = 'Remove VPN connection program';
	$text['설정 -> 앱 (앱 및 기능)에서 프로그램을 삭제할 수 있습니다.'] = 'You can remove the program from Settings -> Apps (Apps & Features).';
	$text['해외 사용자의 경우, 접속이 잘되지 않거나 인터넷 속도가 느리다면 다른 서버를 선택해 접속해 자신에게 맞는 서버를 찾아 사용합니다.'] = 'If the connection is not good or the Internet speed is slow, select other server to connect to and find a server that suits you.';

	$title = "Windows 10 ".$vpnname."VPN ".$subvpnname." Connection";
	$description = "Windows 10 ".$vpnname."VPN Connection Method";
} elseif ($browserlang == "zh") {
	$text['상단으로 이동'] = '转到顶部';

	//win7
	$text['Windows 7 VPN 접속 방법'] = '如何在Windows 7中连接到VPN';
	$text['"제어판 ->  프로그램"에서 접속 프로그램을 삭제할 수 있습니다.'] = '您可以从控制面板->程序中删除程序。';
	$text['접속하기'] = '连接';

	//win7 IKEv2M
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] ='将鼠标指针放在网络（或WiFi）连接托盘图标上，点击"鼠标右键"后选择"打开网络和共享中心"。';
	$text['"네트워크 설정 변경" 아래의 "새 연결 또는 네트워크 설정"을 클릭합니다.'] = '点击"更改网络设置"下面的"新连接或网络设置"。';
	$text['"회사에 연결"을 선택하고 "다음"을 클릭합니다.'] = '选择"连接到公司"并点击"下一个"。';
	$text['"아니요, 새 연결을 만듭니다."를 선택하고 "다음"을 클릭합니다.'] = '选择"不，创建新连接"并点击"下一个"。';
	$text['"내 인터넷 연결 사용(VPN)"을 클릭합니다.'] = '点击"使用我的网络连接（VPN）"。';
	$text['"인터넷 주소"에 아래 서버 주소 중 하나를 선택해 입력하고 "대상 이름"에 "'.$brand_name.'"를 입력하고, "지금 연결하지 않고 나중에 연결할 수 있도록 설정해 놓기만 함"을 선택해 활성화하고 "다음"을  클릭합니다.'] = '在"网址"中选择以下服务器地址中的一个，在"目标名称"中输入"'.$brand_name.'"，并选择"现在不连接，只设置以后可以连接"激活并点击"下一个"。';
	$text['서버주소'] = '서버주소';
	$text['사용자 이름과 암호에 "'.$vpnid.'"와(과) 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = '在用户名和密码中输入"'.$vpnid.'"和密码，"域名"以空格清空。';
	$text['사용자 이름과 암호에 '.$account_url.'에서 생성한 아이디와 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = '在用户名和密码中输入'.$account_url.'生成的ID和密码，"域名"以空格清空。';
	$text['"만들기"와 "닫기"를 차례로 클릭하여 내용을 저장하고 설정 창을 닫습니다.'] = '依次点击"创建"和"关闭"，保存内容并关闭配置窗口。';
	$text['"<strong>어댑터 설정 변경</strong>"을 클릭합니다.'] = '点击"<strong>适配器设置变更</strong>"。';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = $brand_name.'将鼠标放在适配器上，点击鼠标<strong>右</strong>按钮出现的菜单中，选择"<strong>属性</strong>。';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = '打开属性窗口后，选择"网络"标签。选择网络协议版本4（TCP/IPv 4）后点击"属性"。';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = '如图所示，点击<strong>高级</strong>，在<strong>远程网络上选择基本网关使用</strong>，激活并点击几次确认，保存变更内容。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 선택하면 나타나는 "연결" 버튼을 클릭하여 접속할 수 있습니다.'] = '点击网络（或WiFi）连接托盘图标，如图所示，选择'.$brand_name.'图标可点击"连接"按钮进行连接。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "IPany (연결됨)" 아이콘을 선택하면 나타나는 "연결 끊기" 버튼을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标，如图所示，选择"'.$brand_name.'（连接）"图标，点击"断开连接"按钮。';
	$text['네트워크(또는 WiFi)연결 트레이 아이콘을 클릭합니다. "IPany"에 마우스를 올리고 마우스 오른쪽 버튼을 클릭한 후 "속성"을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标。"将鼠标放在IPany"上，点击鼠标右键后点击"属性"。';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = '输入要变更为"目标主机名或IP地址"的服务器地址，并点击"确认"按钮。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] = '将鼠标指针放在网络（或WiFi）连接托盘图标上，点击"鼠标右键"后选择"打开网络和共享中心"。';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = '点击"更改适配器设置"。';
	$text[$brand_name.'에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "삭제"를 선택합니다.'] = '将鼠标指针放在'.$brand_name.'上，点击"鼠标右键"后选择"删除"。';

	//win10 pptpm
	$text['<strong>PPTP VPN 접속 직접 설정 방법</strong>입니다.'] = '<strong>PPTP VPN连接直接设置方法</strong>。';
	$text['PPTP 접속 직접 설정하기'] = 'PPTP 접속 직접 설정하기';
	$text['여기서는 직접 PPTP 접속을 설정하는 방법을 설명합니다.'] = '这里介绍直接设置PPTP连接的方法。';
	$text['"PPTP(지점 간 터널링 포르토콜)" 선택'] = '选择"PPTP（分店间隧道协议）"';
	$text['PPTP 접속이 가능한 서버는 아래와 같습니다.'] = '可连接PPTP的服务器如下。';

	//win10 pptp
	$text['<strong>PPTP VPN 접속 방법</strong>입니다.'] = '<strong>PPTP VPN连接方法</strong>。';
	$text['예전에 사용하던 VPN 방식입니다. 방화벽이나 일부 오래된 공유기를 사용는 환경에서는 접속이 가능하지 않을 수 있습니다(619 오류 발생)'] = '是以前使用过的VPN方式在使用防火墙或部分旧共享设备的环境下，可能无法连接（发生619错误）';
	$text['PPTP 방식은 접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "접속 설정 방법"을 확인하세요.'] = 'PPTP方式不安装连接程序，也可以通过Windows自身简单的VPN连接设置连接。如果您不想安装程序，想直接设置连接，请点击这里确认"连接设置方法"。';
	$text['VPN 방식을 "PPTP"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = '选择VPN方式为"PPTP"，选择连接服务器后点击"连接"即可连接。';
	$text['공유기 문제나 방화벽으로 차단되어 있어 접속할 수 없는 경우입니다. 다른 VPN 방식으로 접속해야 합니다.'] = '因为共享机问题或防火墙被切断，所以无法连接。要用其他VPN方式连接。';


	//win10 IKEv2M
	$text['<strong>IKEv2 VPN 접속 직접 설정 방법</strong>입니다. 위 탭에서 다른 VPN 방식을 확인할 수 있습니다.'] = '<strong>IKEv2 VPN连接直接设置方法</strong>。可以在上面的标签中确认其他VPN方式。';
	$text['여기서는 직접 IKEv2 접속을 설정하는 방법을 설명합니다.'] = '这里介绍直接设置IKEv2连接的方法。';
	$text['직접 설정이 번거롭다면 통합 접속프로그램으로 간편하게 접속할 수 있습니다. 여기를 클릭해 프로그램 설치 방법을 확인하세요.'] = '如果直接设置很麻烦的话，可以利用安装程序简单地设置连接设置。点击这里确认程序安装方法。';
	$text['IKEv2 접속 직접 설정하기'] = '直接设置IKEv2连接';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 "네트워크 설정"을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标，点击"网络设置"。';
	$text['좌측 창에서 "VPN"을 선택하고 오른쪽 창에서 "VPN 연결 추가"를 클릭합니다.'] = '左侧窗口选择"VPN"，右窗口点击"添加VPN连接"。';
	$text['"VPN 연결 추가" 창이 열리면 아래와 같이 각 항목을 입력 또는 선택하고 "저장"을 클릭합니다.'] = '如果打开"添加VPN连接"窗口，请输入或选择以下各项，并点击"保存"。';
	$text['VPN 공급자'] = 'VPN供应商';
	$text['"Windows(기본 제공)" 선택'] = '选择"Windows（基本提供）"';
	$text['연결 이름'] = '连接名称';
	$text['"'.$brand_name.'" 입력'] = '输入'.$brand_name;
	$text['서버 이름 또는 주소'] = '服务器名称或地址';
	$text['아래 서버 주소 중 하나를 선택해 입력'] = '选择下列服务器地址中的一个输入';
	$text['VPN 종류'] = 'VPN种类';
	$text['"IKEv2" 선택'] = '选择"IKEv2"';
	$text['로그인 정보 입력'] = '输入登录信息';
	$text['"사용자 이름 및 암호" 선택'] = '选择"用户名和密码"';
	$text['사용자 이름(옵션)'] = '用户名（选项）';
	$text['"'.$vpnid.'"을(를) 입력합니다.'] = '输入"'.$vpnid.'"';
	$text[$account_url.'에서 생성한 아이디를 입력합니다.'] = '输入在'.$account_url.'中生成的ID。';
	$text['암호(옵션)'] = '密码（选项）';
	$text['"'.$vpnid.'" 생성 시 같이 입력한 비밀번호를 입력합니다.'] = '输入生成"'.$vpnid.'"时一起输入的密码。';
	$text[$account_url.'에서 생성한 아이디의 비밀번호를 입력합니다.'] = '输入在'.$account_url.'中生成的ID的密码。';
	$text['관련 설정의 "<strong>어댑터 옵션 변경</strong>"을 클릭합니다.'] ='点击相关设置的"<strong>适配器选项变更</strong>"。';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = $brand_name.'将鼠标放在适配器上，点击鼠标<strong>右</strong>按钮出现的菜单中，选择"<strong>属性</strong>"。';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = '打开属性窗口后，选择"网络"标签。选择网络协议版本4（TCP/IPv 4）后点击"属性"。';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = '如图所示，点击"<strong>高级</strong>"，在"<strong>远程网络上选择基本网关使用</strong>"，激活并点击几次确认，保存变更内容。';
	$text['모든 설정이 끝났다면, VPN에 생성된 '.$brand_name.'를 선택하고 "연결"을 클릭하여 바로 접속할 수 있습니다.'] = '如果所有设置都已完成，您可以选择VPN中生成的'.$brand_name.'并点击"连接"直接连接。';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = '登录成功后，"账户管理"中选择的固定眼部疲劳将利用网络。';
	$text['접속 끊기'] = '断开连接';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.' (연결됨)" 아이콘을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标，并单击'.$brand_name.'图标。';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.' 연결됨" 을 선택하고 "연결 끊기"를 클릭합니다.'] = '打开"网络和网络"窗口后，选择'.$brand_name.'并点击"断开连接"。';
	$text['다시 접속하기'] = '다시 접속하기';
	$text['접속 프로그램을 설치하거나 접속 설정을 만들었다면 언제든 아래의 방법으로 다시 접속할 수 있습니다.'] = '如果安装了连接程序或设置了连接设置，随时都可以用以下方法再次连接。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标，并点击'.$brand_name.'图标。';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "연결"을 클릭합니다.'] = '打开"网络和网络"窗口，选择'.$brand_name.'并点击"连接"。';
	$text['전에 "암호 저장"을 선택했었다면 바로 접속됩니다.'] = '如果您之前选择了"保存密码"，则立即连接。';
	$text['전에 입력하지 않았었다면 접속 로그인 창이 열립니다. 사용자 이름과 암호를 입력하고 "확인"을 클릭하여 접속할 수 있습니다.'] = '如果之前没有输入，将会打开登录窗口。输入用户名和密码，点击"确认"即可登录。';
	$text['접속 서버 변경 방법'] = '连接服务器更改方法';
	$text[$brand_name.'는 다중 접속 서버를 제공합니다. 언제든 원한다면 자신이 사용 중인 인터넷과 잘 맞는 서버를 선택해 접속할 수 있습니다. 접속 서버를 변경하는 방법은 아래와 같습니다.'] = $brand_name.'提供多个连接服务器。随时都可以选择适合自己使用的网络的服务器登录。更改连接服务器的方法如下。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하고 "네트워크 및 공유 센터 열기"를 선택합니다.'] = '将鼠标指针放在网络（或WiFi）连接托盘图标上，点击鼠标右键，选择"打开网络和共享中心"。';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = '点击"更改适配器设置"。';
	$text['"'.$brand_name.'"에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하면 나타나는 메뉴 중 속성을 선택합니다.'] = '将鼠标指针放在"'.$brand_name.'"上，点击鼠标右键，在菜单中选择属性。';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = '输入要变更为"目标主机名或IP地址"的服务器地址，并点击"确认"按钮。';
	$text['IKEv2 접속이 가능한 서버는 아래와 같습니다.'] = 'IKEv2可连接的服务器如下。';
	$text['접속에 실패하면 접속 프로그램의 "연결 상태"에서 접속 실패 원인과 "오류 번호"를 확인할 수 있습니다.'] = '如果连接失败，您可以在连接程序"连接状态"中确认连接失败的原因和"错误号码"。';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = '点击网络（或WiFi）连接托盘图标，并点击"'.$brand_name.'"图标。';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "제거"를 클릭합니다.'] = '打开"网络和网络"窗口后，选择"'.$brand_name.'"并点击"删除"。';

	//OpenvpnS
	$text['<strong>OpenVPN 이중 암호화</strong> 접속 방법입니다. 중국에서 IKEv2 접속에 문제가 있다면 이 방법을 이용합니다. Stunnel이라는 암호화 터널을 미리 구성하여 그 터널을 통해 OpenVPN 접속이 가능하게 하는 방식입니다.'] = '<strong>OpenVPN双重加密</strong>连接方法。在中国IKEv2连接有问题的话就用这个方法提前组成叫做Stunnel的加密隧道，通过那个隧道可以连接OpenVPN。';
	$text['VPN 방식을 "OpenVPNSSL"로 선택합니다. OpenVPNSSL 접속을 위해서는 OpenVPN과 Stunnel 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = '选择VPN方式为"OpenVPNSSL"。为了连接OpenVPN，需要安装OpenVPN和Stunnel程序。如果没有安装，将自动安装。';

	//Openvpn
	$text['<strong>OpenVPN 접속 방법</strong>입니다. IKEv2 접속이 가능하지 않다면 이방법을 이용하세요. 하지만, 중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL(이중 암호화 방식)을 이용하세요.'] = '<strong>OpenVPN连接方法</strong>。如果不能连接IKEv2，请使用异邦法。但是，在中国不能连接OpenVPN。请使用OpenVPN SSL（双重加密方式）。';
	$text['통합 접속 프로그램을 설치하지 않았다면, 아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = '如果没有安装集成连接程序，请点击下面的下载按钮下载安装文件。';
	$text['VPN 방식을 "OpenVPN"로 선택합니다. OpenVPN 접속을 위해서는 OpenVPN 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = '选择VPN方式为"OpenVPN"。为了连接OpenVPN，需要安装OpenVPN程序。如果没有安装，将自动安装。';
	$text['프로그램 설치 시 디바이스 설치를 묻는 창이 뜨면 반드시 "Install"을 선택해야합니다.'] = '安装程序时，如果出现询问设备安装的窗口，必须选择"Install"。';
	$text['접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = '选择登录服务器后点击"登录"即可登录。';
	$text['원인을 알수 없는 경우, OpenVPN GUI 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭한 후 "View Log"를 선택하면 메모장이 열리며 접속 로그를 확인할 수 있습니다.'] = '如果不知道原因，可以在OpenVPN GUI托盘图标上上传鼠标指针，点击鼠标右键后选择"View Log"，即可打开记事本确认连接日志。';
	$text['접속 로그 내용에 따른 접속 실패 원인과 해결 방법입니다.'] = '根据登录日志内容的连接失败原因和解决方法。';
	$text['(표)OpenVPN 오류 로그 - ipany.net'] = '（表）OpenVPN错误日志-'.$brand_name;
	$text['접속 로그 내용'] = '登录日志内容';
	$text['접속 실패 원인 및 해결 방법'] = '连接失败原因及解决方法';
	$text['AUTH: Received control message: AUTH_FAILED'] = 'AUTH: Received control message: AUTH_FAILED';
	$text['Username 이나 Password를 잘못 입력하거나, 만기일이 지나거나, 이미 다른 기기나 컴퓨터에서 접속되어 있는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. '.$account_url.'에서 계정 상태를 확인하세요.'] = '错误输入Username或Password，或者过期，或者已经在其他机器或电脑上连接。'.$brand_name.'服务不能同时通过同一账户进行双重连接。请在'.$account_url.'中确认账户状态。';
	$text['RESOLVE: Cannot resolve host address: ipany...'] = 'RESOLVE: Cannot resolve host address: ipany...';
	$text['DNS 문제로 IPany VPN 서버를 찾지 못하는 경우입니다. 컴퓨터의 DNS 설정에서 DNS 서버 주소를 168.126.63.1로 변경해 주세요.'] = '因为DNS问题找不到IPany VPN服务器。请将DNS服务器的地址从您计算机的DNS设置改为168.126.63.1。';
	$text['All TAP-Win32 adapters on this system are currently in use'] = 'All TAP-Win32 adapters on this system are currently in use';
	$text['가상 드라이브가 이미 실행되고 있는 경우입니다. 컴퓨터를 재부팅하고 접속합니다.'] = '虚拟驱动器已运行。重新启动并连接电脑';
	$text['"Unable to connect because your certificate is not yet valid. Check that your system time is correct" 라는 메세지가 뜨는 경우'] = '出现"Unable to connect because your certificate is not yet valid. Check that your system time is correct"的信息时';
	$text['사용자 컴퓨터의 현재 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간을 현재시간으로 조정한 후 접속합니다.'] = '用户计算机的当前时间是错误的。将电脑的时间调整到当前时间后再连接。';
	$text['TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)'] = 'TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)';
	$text['사용자의 인터넷 연결 상태가 불안하거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다. 또 다른 이유는 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = '如果用户的网络连接状态不稳定，或者从国外连接，当地网络和'.$brand_name.'线路之间的路径不好。如果使用共享机的话关掉10分钟左右再打开另一个理由是电脑的时间有问题。请确认电脑的时间设置。';
	$text['TLS Error: Unroutable control packet received'] = 'TLS Error: Unroutable control packet received';
	$text['사용자의 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = '用户电脑的时间有问题。请确认电脑的时间设置。';
	$text['UDP/TCP: connect to ipany... failed'] = 'UDP/TCP: connect to ipany... failed';
	$text['IPany VPN 서버로 접속할 수 없는 경우입니다. 인터넷이 연결되어 있지 않거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다.'] = '无法连接到'.$brand_name.' VPN服务器。如果网络没有连接，或者从国外连接，当地网络和IPany线路之间的路径不好。如果使用共享机的话关掉10分钟左右再打开';
	$text['TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds'] = 'TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds';
	$text['OpenVPN 이중 암호 방식 접속은 OpenVPN 접속 전에 Stunnel이 먼저 실행되어 있어야 합니다. Stunnel이 실행되어 있지 않아 발생하는 문제입니다. Stunnel를 먼저 실행하고 다시 접속합니다.'] = 'OpenVPN双重密码连接必须在OpenVPN连接前先运行Stunnel。因为没有运行Stunnel所以发生的问题先运行Stunel再连接';
	$text['OpenVPN 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = '如果不使用OpenVPN程序，可以在这里删除。';
	$text['OpenVPN과 Stunnel 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = '如果不使用OpenVPN和Stunnel程序的话可以在这里删除';


	//win10
	$text['직접설정'] = '自行设定';
	$text['이중암호화'] = '双重加密';
	$text['Windows 10 VPN 접속 방법'] = '如何在Windows 10中连接到VPN';
	$text['다른 디바이스 접속 방법 보러 가기'] = '去看看如何从其他设备连接';
	$text['아래 방법으로 VPN 접속을 할 수 있습니다. 접속아이디에 "'.$vpnid.'"을(를) 사용하세요.'] = '您可以通过以下方式连接到VPN。请使用"'.$vpnid.'"作为VPN连接ID';
	$text['가장 많이 사용되는 <strong>IKEv2 VPN 접속 방법</strong>입니다.'] = '这是最常用的IKEv2 VPN连接方法。';
	$text['접속 프로그램 설치 및 접속'] = '连接程序的安装和连接';
	$text['아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = '单击下面的下载按钮以下载安装文件。';
	$text['통합 접속프로그램 다운받기'] = '下载集成连接程序';
	$text['접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "직접 접속 설정 방법"을 확인하세요.'] = '您可以使用Windows本身的简单VPN连接设置进行连接，而无需安装连接程序。 如果您不想安装该程序并想要自己建立连接，请单击此处查看"如何自行设置"。';
	$text['브라우저의 다운로드 관련 메세지가 나타나면 "저장"을 선택하여 다운로드한 설치파일을 저장합니다.'] = '当浏览器的下载消息出现时，选择"保存"以保存下载的安装文件。';
	$text['다운로드가 끝나고 "폴더 열기"을 선택하면 다운로드된 파일이 저장된 폴더가 열리게 됩니다.'] = '下载完成后，选择"打开文件夹"以打开保存下载文件的文件夹。';
	$text['zip 파일의 압축을 풀어주면 나오는 실행 파일을 더블 클릭하여 실행합니다.'] = '解压缩zip文件后，双击可执行文件以运行它。';
	$text['그림과 같이 "Windows PC 보호" 창이 열린다면 "추가 정보"를 클릭하면 "실행" 버튼이 보이게 됩니다. "실행" 버튼을 클릭합니다.'] = '如果如图所示打开" Windows保护您的PC"窗口，请单击"更多信息"，您将看到一个"运行"按钮。 单击"仍然运行"按钮。';
	$text['그림과 같이 "사용자 계정 컨트롤" 창이 열린다면 "예"를 선택합니다.'] = '如果如图所示打开"用户帐户控制"窗口，请选择"是"。';
	$text['프로그램 설치를 마치고, 바탕화면 바로가기나 시작 메뉴에서 IPanyVPN을 클릭하여 프로그램을 실행합니다.'] = '安装程序后，从桌面快捷方式或"开始"菜单中单击IPanyVPN以运行该程序。';
	$text['통합 접속 프로그램이 열리면,'] = '当集成访问程序打开时，';
	$text['접속아이디에 "'.$vpnid.'"을(를) 입력하고, 비밀번호를 입력하세요.'] = '在访问ID中输入"'.$vpnid.'"，然后输入密码。';
	$text[$account_url.'에서 생성한 계정의 접속아이디와 비밀번호를 입력합니다.'] = '输入在'.$account_url.'中创建的连接ID和密码。';
	$text['VPN 방식을 "IKEv2"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = '您可以通过选择" IKEv2"作为VPN方法，选择连接服务器并单击"连接"来进行连接。';
	$text['VPN 방식'] = 'VPN方式';
	$text['IKEv2 접속에 문제가 있다면, Openvpn 접속 방식을 선택하세요. (중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL을 사용하세요.)'] = '如果在连接IKEv2时遇到问题，请选择Openvpn连接方法。 （OpenVPN连接在中国不可用。请改用OpenVPN SSL。）';
	$text['접속 서버'] = '连接服务器';
	$text['IPany는 다중 접속 서버를 제공합니다. 접속이 원할하지 않다면 다른 서버를 선택해 접속할 수 있습니다.'] = $brand_name.'提供了多个访问服务器。 如果连接出现问题，则可以选择另一台服务器进行连接。';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = '如果连接成功，您将使用在"帐户管理"中选择的韩文IP的Internet。';
	$text['<span class="badge badge-danger">중국</span> 중국에서 접속 시 VPN 접속 후에도 구글 페이스북이 열리지 않는다면 DNS 서버 설정을 변경해야 합니다. 방법을 확인하려면 여기를 클릭하세요.'] = '<span class="badge badge-danger">中国</span> 从中国连接时，如果在VPN连接后仍未打开Goog​​le和Facebook，则需要更改DNS服务器设置。 单击此处查看操作方法。';
	$text[$osname.'에서 DNS 서버를 한국 DNS 서버로 변경하는 방법입니다.'] = '这是将'.$osname.'中的DNS服务器更改为韩文DNS服务器的方法。';
	$text['윈도우 데스크톱 화면의 오른쪽 아래의 네트워크 트레이 아이콘에 마우스를 올리고 마우스 오른 쪽 버튼을 클릭합니다. <strong>네트워크 및 공유 센터 열기</strong>를 선택합니다.'] = '将鼠标移到Windows桌面屏幕右下角的网络托盘图标上，然后单击鼠标右键。 选择<strong>打开网络和共享中心</strong>。';
	$text['PC가 인터넷에 연결된 이더넷이나 WiFi의 연결을 클릭합니다.'] = '单击您的PC连接到Internet的以太网或WiFi连接。';
	$text['속성을 클릭합니다.'] = '单击属性。';
	$text['인터넷 프로토콜 버전4(TCP/IPv4)를 더블 클릭합니다.'] = '双击" Internet协议版本4（TCP / IPv4）"。';
	$text['"다음 DNS 서버 주소 사용"을 선택하고 그림과 같이 DNS 서버 주소를 입력합니다.'] = '选择"使用以下DNS服务器地址"，然后输入DNS服务器地址，如图所示。';
	$text['"확인" 및 "닫기" 버튼을 연속으로 선택하여 변경 내용을 적용합니다.  PC를 재부팅 합니다.'] = '依次选择"确定"和"关闭"按钮以应用更改。 重新启动您的PC。';
	$text['이 방법으로도 해결이되지 않는다면 <a href="connects_rpi_rpi.php">PI보드를 이용한 VPN 접속 방법</a>을 사용해야 합니다.'] = '如果这不起作用，<a href="connects_rpi_rpi.php">则应通过PI板使用VPN连接方法。</a>';
	$text['접속 장애 확인'] = '检查连接失败';
	$text['접속에 실패하면 접속 실패창이 뜨게됩니다. 여기서 접속 실패 원인을 확인할 수 있습니다.'] = '如果连接失败，将出现"连接失败"窗口。 您可以在此处检查连接失败的原因。';
	$text['주요 "오류 번호"에 따른 접속 실패 원인과 해결 방법입니다.'] = '这些是根据主要"错误号"的连接失败的原因和解决方案。';
	$text['오류'] = '错误';
	$text['원인 및 해결방법'] = '原因及解决方法';
	$text['접속 계정의 사용자 이름, 비밀번호가 잘못되거나, 만기일이 지났거나, 이미 접속되어 있는데 다시 접속을 시도하는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. IPany.net 홈페이지의 "<a href="staticip.php">계정 관리</a>"에서 해당 계정 상태를 확인합니다.'] = '访问帐户的用户名和密码不正确，到期日期已过期，或者即使已连接也尝试重新连接。 '.$brand_name.'服务不允许使用同一帐户同时进行双重访问。 在'.$brand_name.'主页上的" <a href="staticip.php">帐户管理</a>"中检查帐户的状态。';
	$text['접속 서버를 찾지 못해 발생하는 오류입니다. 인터넷 연결이 되어있지 않은 경우, DNS 오류, 방화벽으로 차단된 경우입니다. DNS 오류의 경우는 컴퓨터의 DNS 서버 설정을 "168.126.63.1"로 변경하여 해결 할 수 있습니다. 방화벽으로 차단된 경우는 다른 VPN 방식으로 접속해야 합니다.'] = '当找不到连接服务器时，会发生此错误。 如果没有Internet连接，则防火墙将阻止DNS错误或VPN连接。 通过将计算机的DNS服务器设置更改为" 168.126.63.1"，可以解决DNS错误。 如果它被防火墙阻止，则需要使用其他VPN方法进行连接。';
	$text['오류87 "매개변수가 틀립니다."는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = '错误87"参数不正确"是由于Windows操作系统本身存在问题。 <a href="howto.php">问题排查页面</a>中说明了该解决方案。';
	$text['오류809는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = '错误809是因为Windows OS本身的问题。 <a href="howto.php">问题排查页面</a>中说明了该解决方案。';
	$text['접속기 삭제'] = '删除VPN连接程序';
	$text['설정 -> 앱 (앱 및 기능)에서 프로그램을 삭제할 수 있습니다.'] = '您可以从设置->应用程序（应用程序和功能）中删除程序。';
	$text['해외 사용자의 경우, 접속이 잘되지 않거나 인터넷 속도가 느리다면 다른 서버를 선택해 접속해 자신에게 맞는 서버를 찾아 사용합니다.'] = '如果连接不好或互联网速度很慢，请选择另一台服务器连接并找到适合您的服务器。';

	$title = "Windows 10 ".$vpnname."VPN ".$subvpnname." 连接";
	$description = "Windows 10 ".$vpnname."VPN 连接方式";
} else {
	$text['상단으로 이동'] = '상단으로 이동';

	//win7
	$text['Windows 7 VPN 접속 방법'] = 'Windows 7 VPN 접속 방법';
	$text['"제어판 ->  프로그램"에서 접속 프로그램을 삭제할 수 있습니다.'] = '"제어판 ->  프로그램"에서 접속 프로그램을 삭제할 수 있습니다.';
	$text['접속하기'] = '접속하기';

	//win7 IKEv2M
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] ='네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.';
	$text['"네트워크 설정 변경" 아래의 "새 연결 또는 네트워크 설정"을 클릭합니다.'] = '"네트워크 설정 변경" 아래의 "새 연결 또는 네트워크 설정"을 클릭합니다.';
	$text['"회사에 연결"을 선택하고 "다음"을 클릭합니다.'] = '"회사에 연결"을 선택하고 "다음"을 클릭합니다.';
	$text['"아니요, 새 연결을 만듭니다."를 선택하고 "다음"을 클릭합니다.'] = '"아니요, 새 연결을 만듭니다."를 선택하고 "다음"을 클릭합니다.';
	$text['"내 인터넷 연결 사용(VPN)"을 클릭합니다.'] = '"내 인터넷 연결 사용(VPN)"을 클릭합니다.';
	$text['"인터넷 주소"에 아래 서버 주소 중 하나를 선택해 입력하고 "대상 이름"에 "'.$brand_name.'"를 입력하고, "지금 연결하지 않고 나중에 연결할 수 있도록 설정해 놓기만 함"을 선택해 활성화하고 "다음"을  클릭합니다.'] = '"인터넷 주소"에 아래 서버 주소 중 하나를 선택해 입력하고 "대상 이름"에 "'.$brand_name.'"를 입력하고, "지금 연결하지 않고 나중에 연결할 수 있도록 설정해 놓기만 함"을 선택해 활성화하고 "다음"을  클릭합니다.';
	$text['서버주소'] = '서버주소';
	$text['사용자 이름과 암호에 "'.$vpnid.'"와(과) 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = '사용자 이름과 암호에 "'.$vpnid.'"와(과) 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.';
	$text['사용자 이름과 암호에 '.$account_url.'에서 생성한 아이디와 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.'] = '사용자 이름과 암호에 '.$account_url.'에서 생성한 아이디와 비밀번호를 입력하고 "도메인"은 공란으로 비워둡니다.';
	$text['"만들기"와 "닫기"를 차례로 클릭하여 내용을 저장하고 설정 창을 닫습니다.'] = '"만들기"와 "닫기"를 차례로 클릭하여 내용을 저장하고 설정 창을 닫습니다.';
	$text['"<strong>어댑터 설정 변경</strong>"을 클릭합니다.'] = '"<strong>어댑터 설정 변경</strong>"을 클릭합니다.';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = $brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = '속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = '그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 선택하면 나타나는 "연결" 버튼을 클릭하여 접속할 수 있습니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 선택하면 나타나는 "연결" 버튼을 클릭하여 접속할 수 있습니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "IPany (연결됨)" 아이콘을 선택하면 나타나는 "연결 끊기" 버튼을 클릭합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "IPany (연결됨)" 아이콘을 선택하면 나타나는 "연결 끊기" 버튼을 클릭합니다.';
	$text['네트워크(또는 WiFi)연결 트레이 아이콘을 클릭합니다. "IPany"에 마우스를 올리고 마우스 오른쪽 버튼을 클릭한 후 "속성"을 클릭합니다.'] = '네트워크(또는 WiFi)연결 트레이 아이콘을 클릭합니다. "IPany"에 마우스를 올리고 마우스 오른쪽 버튼을 클릭한 후 "속성"을 클릭합니다.';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = '"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "네트워크 및 공유 센터 열기"를 선택합니다.';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = '"어댑터 설정 변경"을 클릭합니다.';
	$text[$brand_name.'에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "삭제"를 선택합니다.'] = $brand_name.'에 마우스 포인터를 올리고 "마우스 오른쪽 버튼"을 클릭한 후 "삭제"를 선택합니다.';

	//win10 pptpm
	$text['<strong>PPTP VPN 접속 직접 설정 방법</strong>입니다.'] = '<strong>PPTP VPN 접속 직접 설정 방법</strong>입니다.';
	$text['PPTP 접속 직접 설정하기'] = 'PPTP 접속 직접 설정하기';
	$text['여기서는 직접 PPTP 접속을 설정하는 방법을 설명합니다.'] = '여기서는 직접 PPTP 접속을 설정하는 방법을 설명합니다.';
	$text['"PPTP(지점 간 터널링 포르토콜)" 선택'] = '"PPTP(지점 간 터널링 포르토콜)" 선택';
	$text['PPTP 접속이 가능한 서버는 아래와 같습니다.'] = 'PPTP 접속이 가능한 서버는 아래와 같습니다.';

	//win10 pptp
	$text['<strong>PPTP VPN 접속 방법</strong>입니다.'] = '<strong>PPTP VPN 접속 방법</strong>입니다.';
	$text['예전에 사용하던 VPN 방식입니다. 방화벽이나 일부 오래된 공유기를 사용는 환경에서는 접속이 가능하지 않을 수 있습니다(619 오류 발생)'] = '예전에 사용하던 VPN 방식입니다. 방화벽이나 일부 오래된 공유기를 사용는 환경에서는 접속이 가능하지 않을 수 있습니다(619 오류 발생)';
	$text['PPTP 방식은 접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "접속 설정 방법"을 확인하세요.'] = 'PPTP 방식은 접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "접속 설정 방법"을 확인하세요.';
	$text['VPN 방식을 "PPTP"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = 'VPN 방식을 "PPTP"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.';
	$text['공유기 문제나 방화벽으로 차단되어 있어 접속할 수 없는 경우입니다. 다른 VPN 방식으로 접속해야 합니다.'] = '공유기 문제나 방화벽으로 차단되어 있어 접속할 수 없는 경우입니다. 다른 VPN 방식으로 접속해야 합니다.';

	//win10 IKEv2M
	$text['<strong>IKEv2 VPN 접속 직접 설정 방법</strong>입니다. 위 탭에서 다른 VPN 방식을 확인할 수 있습니다.'] = '<strong>IKEv2 VPN 접속 직접 설정 방법</strong>입니다. 위 탭에서 다른 VPN 방식을 확인할 수 있습니다.';
	$text['여기서는 직접 IKEv2 접속을 설정하는 방법을 설명합니다.'] = '여기서는 직접 IKEv2 접속을 설정하는 방법을 설명합니다.';
	$text['직접 설정이 번거롭다면 통합 접속프로그램으로 간편하게 접속할 수 있습니다. 여기를 클릭해 프로그램 설치 방법을 확인하세요.'] = '직접 설정이 번거롭다면 통합 접속프로그램으로 간편하게 접속할 수 있습니다. 여기를 클릭해 프로그램 설치 방법을 확인하세요.';
	$text['IKEv2 접속 직접 설정하기'] = 'IKEv2 접속 직접 설정하기';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 "네트워크 설정"을 클릭합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 "네트워크 설정"을 클릭합니다.';
	$text['좌측 창에서 "VPN"을 선택하고 오른쪽 창에서 "VPN 연결 추가"를 클릭합니다.'] = '좌측 창에서 "VPN"을 선택하고 오른쪽 창에서 "VPN 연결 추가"를 클릭합니다.';
	$text['"VPN 연결 추가" 창이 열리면 아래와 같이 각 항목을 입력 또는 선택하고 "저장"을 클릭합니다.'] = '"VPN 연결 추가" 창이 열리면 아래와 같이 각 항목을 입력 또는 선택하고 "저장"을 클릭합니다.';
	$text['VPN 공급자'] = 'VPN 공급자';
	$text['"Windows(기본 제공)" 선택'] = '"Windows(기본 제공)" 선택';
	$text['연결 이름'] = '연결 이름';
	$text['"'.$brand_name.'" 입력'] = '"'.$brand_name.'" 입력';
	$text['서버 이름 또는 주소'] = '서버 이름 또는 주소';
	$text['아래 서버 주소 중 하나를 선택해 입력'] = '아래 서버 주소 중 하나를 선택해 입력';
	$text['VPN 종류'] = 'VPN 종류';
	$text['"IKEv2" 선택'] = '"IKEv2" 선택';
	$text['로그인 정보 입력'] = '로그인 정보 입력';
	$text['"사용자 이름 및 암호" 선택'] = '"사용자 이름 및 암호" 선택';
	$text['사용자 이름(옵션)'] = '사용자 이름(옵션)';
	$text['"'.$vpnid.'"을(를) 입력합니다.'] = '"'.$vpnid.'"을(를) 입력합니다.';
	$text[$account_url.'에서 생성한 아이디를 입력합니다.'] = $account_url.'에서 생성한 아이디를 입력합니다.';
	$text['암호(옵션)'] = '암호(옵션)';
	$text['"'.$vpnid.'" 생성 시 같이 입력한 비밀번호를 입력합니다.'] = '"'.$vpnid.'" 생성 시 같이 입력한 비밀번호를 입력합니다.';
	$text[$account_url.'에서 생성한 아이디의 비밀번호를 입력합니다.'] = $account_url.'에서 생성한 아이디의 비밀번호를 입력합니다.';
	$text['관련 설정의 "<strong>어댑터 옵션 변경</strong>"을 클릭합니다.'] ='관련 설정의 "<strong>어댑터 옵션 변경</strong>"을 클릭합니다.';
	$text[$brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.'] = $brand_name.' 어댑터에 마우스를 올리고 마우스 <strong>오른쪽</strong> 버튼을 클릭하여 나타나는 메뉴 중 "<strong>속성</strong>"을 선택합니다.';
	$text['속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.'] = '속성 창이 열리면 "네트워킹" 탭을 선택합니다. "인터넷 프로토콜 버전 4 (TCP/IPv4)"를 선택한 후 "속성"을 클릭합니다.';
	$text['그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.'] = '그림과 같이 "<strong>고급</strong>"을 클릭하고 "<strong>원격 네트워크에 기본 게이트웨이 사용</strong>"을 선택하여 활성화하고 몇번의 확인을 클릭하여 변경 내용을 저장합니다.';
	$text['모든 설정이 끝났다면, VPN에 생성된 '.$brand_name.'를 선택하고 "연결"을 클릭하여 바로 접속할 수 있습니다.'] = '모든 설정이 끝났다면, VPN에 생성된 '.$brand_name.'를 선택하고 "연결"을 클릭하여 바로 접속할 수 있습니다.';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = '접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.';
	$text['접속 끊기'] = '접속 끊기';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.' (연결됨)" 아이콘을 클릭합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.' (연결됨)" 아이콘을 클릭합니다.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.' 연결됨" 을 선택하고 "연결 끊기"를 클릭합니다.'] = '"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.' 연결됨" 을 선택하고 "연결 끊기"를 클릭합니다.';
	$text['다시 접속하기'] = '다시 접속하기';
	$text['접속 프로그램을 설치하거나 접속 설정을 만들었다면 언제든 아래의 방법으로 다시 접속할 수 있습니다.'] = '접속 프로그램을 설치하거나 접속 설정을 만들었다면 언제든 아래의 방법으로 다시 접속할 수 있습니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "연결"을 클릭합니다.'] = '"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "연결"을 클릭합니다.';
	$text['전에 "암호 저장"을 선택했었다면 바로 접속됩니다.'] = '전에 "암호 저장"을 선택했었다면 바로 접속됩니다.';
	$text['전에 입력하지 않았었다면 접속 로그인 창이 열립니다. 사용자 이름과 암호를 입력하고 "확인"을 클릭하여 접속할 수 있습니다.'] = '전에 입력하지 않았었다면 접속 로그인 창이 열립니다. 사용자 이름과 암호를 입력하고 "확인"을 클릭하여 접속할 수 있습니다.';
	$text['접속 서버 변경 방법'] = '접속 서버 변경 방법';
	$text[$brand_name.'는 다중 접속 서버를 제공합니다. 언제든 원한다면 자신이 사용 중인 인터넷과 잘 맞는 서버를 선택해 접속할 수 있습니다. 접속 서버를 변경하는 방법은 아래와 같습니다.'] = $brand_name.'는 다중 접속 서버를 제공합니다. 언제든 원한다면 자신이 사용 중인 인터넷과 잘 맞는 서버를 선택해 접속할 수 있습니다. 접속 서버를 변경하는 방법은 아래와 같습니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하고 "네트워크 및 공유 센터 열기"를 선택합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하고 "네트워크 및 공유 센터 열기"를 선택합니다.';
	$text['"어댑터 설정 변경"을 클릭합니다.'] = '"어댑터 설정 변경"을 클릭합니다.';
	$text['"'.$brand_name.'"에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하면 나타나는 메뉴 중 속성을 선택합니다.'] = '"'.$brand_name.'"에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭하면 나타나는 메뉴 중 속성을 선택합니다.';
	$text['"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.'] = '"대상 호스트 이름 또는 IP 주소"에 변경하려는 서버 주소를 입력하고 "확인"버튼을 클릭합니다.';
	$text['IKEv2 접속이 가능한 서버는 아래와 같습니다.'] = 'IKEv2 접속이 가능한 서버는 아래와 같습니다.';
	$text['접속에 실패하면 접속 프로그램의 "연결 상태"에서 접속 실패 원인과 "오류 번호"를 확인할 수 있습니다.'] = '접속에 실패하면 접속 프로그램의 "연결 상태"에서 접속 실패 원인과 "오류 번호"를 확인할 수 있습니다.';
	$text['네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.'] = '네트워크(또는 WiFi) 연결 트레이 아이콘을 클릭하고 그림과 같이 "'.$brand_name.'" 아이콘을 클릭합니다.';
	$text['"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "제거"를 클릭합니다.'] = '"네트워크 및 인터넷" 창이 열리면 "'.$brand_name.'"를 선택하고 "제거"를 클릭합니다.';

	//OpenvpnS
	$text['<strong>OpenVPN 이중 암호화</strong> 접속 방법입니다. 중국에서 IKEv2 접속에 문제가 있다면 이 방법을 이용합니다. Stunnel이라는 암호화 터널을 미리 구성하여 그 터널을 통해 OpenVPN 접속이 가능하게 하는 방식입니다.'] = '<strong>OpenVPN 이중 암호화</strong> 접속 방법입니다. 중국에서 IKEv2 접속에 문제가 있다면 이 방법을 이용합니다. Stunnel이라는 암호화 터널을 미리 구성하여 그 터널을 통해 OpenVPN 접속이 가능하게 하는 방식입니다.';
	$text['VPN 방식을 "OpenVPNSSL"로 선택합니다. OpenVPNSSL 접속을 위해서는 OpenVPN과 Stunnel 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = 'VPN 방식을 "OpenVPNSSL"로 선택합니다. OpenVPNSSL 접속을 위해서는 OpenVPN과 Stunnel 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.';


	//Openvpn
	$text['<strong>OpenVPN 접속 방법</strong>입니다. IKEv2 접속이 가능하지 않다면 이방법을 이용하세요. 하지만, 중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL(이중 암호화 방식)을 이용하세요.'] = '<strong>OpenVPN 접속 방법</strong>입니다. IKEv2 접속이 가능하지 않다면 이방법을 이용하세요. 하지만, 중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL(이중 암호화 방식)을 이용하세요.';
	$text['통합 접속 프로그램을 설치하지 않았다면, 아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = '통합 접속 프로그램을 설치하지 않았다면, 아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.';
	$text['VPN 방식을 "OpenVPN"로 선택합니다. OpenVPN 접속을 위해서는 OpenVPN 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.'] = 'VPN 방식을 "OpenVPN"로 선택합니다. OpenVPN 접속을 위해서는 OpenVPN 프로그램 설치가 필요합니다. 설치되어있지 않다면 자동으로 설치됩니다.';
	$text['프로그램 설치 시 디바이스 설치를 묻는 창이 뜨면 반드시 "Install"을 선택해야합니다.'] = '프로그램 설치 시 디바이스 설치를 묻는 창이 뜨면 반드시 "Install"을 선택해야합니다.';
	$text['접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = '접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.';
	$text['원인을 알수 없는 경우, OpenVPN GUI 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭한 후 "View Log"를 선택하면 메모장이 열리며 접속 로그를 확인할 수 있습니다.'] = '원인을 알수 없는 경우, OpenVPN GUI 트레이 아이콘에 마우스 포인터를 올리고 마우스 오른쪽 버튼을 클릭한 후 "View Log"를 선택하면 메모장이 열리며 접속 로그를 확인할 수 있습니다.';
	$text['접속 로그 내용에 따른 접속 실패 원인과 해결 방법입니다.'] = '접속 로그 내용에 따른 접속 실패 원인과 해결 방법입니다.';
	$text['(표)OpenVPN 오류 로그 - ipany.net'] = '(표)OpenVPN 오류 로그 - ipany.net';
	$text['접속 로그 내용'] = '접속 로그 내용';
	$text['접속 실패 원인 및 해결 방법'] = '접속 실패 원인 및 해결 방법';
	$text['AUTH: Received control message: AUTH_FAILED'] = 'AUTH: Received control message: AUTH_FAILED';
	$text['Username 이나 Password를 잘못 입력하거나, 만기일이 지나거나, 이미 다른 기기나 컴퓨터에서 접속되어 있는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. '.$account_url.'에서 계정 상태를 확인하세요.'] = 'Username 이나 Password를 잘못 입력하거나, 만기일이 지나거나, 이미 다른 기기나 컴퓨터에서 접속되어 있는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. '.$account_url.'에서 계정 상태를 확인하세요.';
	$text['RESOLVE: Cannot resolve host address: ipany...'] = 'RESOLVE: Cannot resolve host address: ipany...';
	$text['DNS 문제로 IPany VPN 서버를 찾지 못하는 경우입니다. 컴퓨터의 DNS 설정에서 DNS 서버 주소를 168.126.63.1로 변경해 주세요.'] = 'DNS 문제로 IPany VPN 서버를 찾지 못하는 경우입니다. 컴퓨터의 DNS 설정에서 DNS 서버 주소를 168.126.63.1로 변경해 주세요.';
	$text['All TAP-Win32 adapters on this system are currently in use'] = 'All TAP-Win32 adapters on this system are currently in use';
	$text['가상 드라이브가 이미 실행되고 있는 경우입니다. 컴퓨터를 재부팅하고 접속합니다.'] = '가상 드라이브가 이미 실행되고 있는 경우입니다. 컴퓨터를 재부팅하고 접속합니다.';
	$text['"Unable to connect because your certificate is not yet valid. Check that your system time is correct" 라는 메세지가 뜨는 경우'] = '"Unable to connect because your certificate is not yet valid. Check that your system time is correct" 라는 메세지가 뜨는 경우';
	$text['사용자 컴퓨터의 현재 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간을 현재시간으로 조정한 후 접속합니다.'] = '사용자 컴퓨터의 현재 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간을 현재시간으로 조정한 후 접속합니다.';
	$text['TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)'] = 'TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)';
	$text['사용자의 인터넷 연결 상태가 불안하거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다. 또 다른 이유는 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = '사용자의 인터넷 연결 상태가 불안하거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다. 또 다른 이유는 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.';
	$text['TLS Error: Unroutable control packet received'] = 'TLS Error: Unroutable control packet received';
	$text['사용자의 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.'] = '사용자의 컴퓨터의 시간이 잘못되어 있는 경우입니다. 컴퓨터의 시간 설정을 확인하세요.';
	$text['UDP/TCP: connect to ipany... failed'] = 'UDP/TCP: connect to ipany... failed';
	$text['IPany VPN 서버로 접속할 수 없는 경우입니다. 인터넷이 연결되어 있지 않거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다.'] = 'IPany VPN 서버로 접속할 수 없는 경우입니다. 인터넷이 연결되어 있지 않거나, 외국에서 접속하는 경우 현지 인터넷과 IPany 회선간 경로가 좋지 않은 경우입니다. 공유기를 사용한다면 공유기를 10분 정도 껐다가 켜고 다시 시도해 봅니다.';
	$text['TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds'] = 'TCP: connect to [AF_INET]127.0.0.1:443 failed, will try again in 5 seconds';
	$text['OpenVPN 이중 암호 방식 접속은 OpenVPN 접속 전에 Stunnel이 먼저 실행되어 있어야 합니다. Stunnel이 실행되어 있지 않아 발생하는 문제입니다. Stunnel를 먼저 실행하고 다시 접속합니다.'] = 'OpenVPN 이중 암호 방식 접속은 OpenVPN 접속 전에 Stunnel이 먼저 실행되어 있어야 합니다. Stunnel이 실행되어 있지 않아 발생하는 문제입니다. Stunnel를 먼저 실행하고 다시 접속합니다.';
	$text['OpenVPN 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = 'OpenVPN 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.';
	$text['OpenVPN과 Stunnel 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.'] = 'OpenVPN과 Stunnel 프로그램도 사용하지 않는다면 여기서 삭제할 수 있습니다.';


	//win10
	$text['직접설정'] = '직접설정';
	$text['이중암호화'] = '이중암호화';
	$text['Windows 10 VPN 접속 방법'] = 'Windows 10 VPN 접속 방법';
	$text['다른 디바이스 접속 방법 보러 가기'] = '다른 디바이스 접속 방법 보러 가기';
	$text['아래 방법으로 VPN 접속을 할 수 있습니다. 접속아이디에 "'.$vpnid.'"을(를) 사용하세요.'] = '아래 방법으로 VPN 접속을 할 수 있습니다. 접속아이디에 "'.$vpnid.'"을(를) 사용하세요.';
	$text['가장 많이 사용되는 <strong>IKEv2 VPN 접속 방법</strong>입니다.'] = '가장 많이 사용되는 <strong>IKEv2 VPN 접속 방법</strong>입니다.';
	$text['접속 프로그램 설치 및 접속'] = '접속 프로그램 설치 및 접속';
	$text['아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.'] = '아래 다운로드 버튼을 클릭하여 설치파일을 다운받습니다.';
	$text['통합 접속프로그램 다운받기'] = '통합 접속프로그램 다운받기';
	$text['접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "직접 접속 설정 방법"을 확인하세요.'] = '접속 프로그램을 설치하지 않고 Windows 자체의 간단한 VPN 접속 설정으로도 접속이 가능합니다. 프로그램 설치를 원하지 않고 접속 설정을 직접하기 원한다면 여기를 클릭해 "직접 접속 설정 방법"을 확인하세요.';
	$text['브라우저의 다운로드 관련 메세지가 나타나면 "저장"을 선택하여 다운로드한 설치파일을 저장합니다.'] = '브라우저의 다운로드 관련 메세지가 나타나면 "저장"을 선택하여 다운로드한 설치파일을 저장합니다.';
	$text['다운로드가 끝나고 "폴더 열기"을 선택하면 다운로드된 파일이 저장된 폴더가 열리게 됩니다.'] = '다운로드가 끝나고 "폴더 열기"을 선택하면 다운로드된 파일이 저장된 폴더가 열리게 됩니다.';
	$text['zip 파일의 압축을 풀어주면 나오는 실행 파일을 더블 클릭하여 실행합니다.'] = 'zip 파일의 압축을 풀어주면 나오는 실행 파일을 더블 클릭하여 실행합니다.';
	$text['그림과 같이 "Windows PC 보호" 창이 열린다면 "추가 정보"를 클릭하면 "실행" 버튼이 보이게 됩니다. "실행" 버튼을 클릭합니다.'] = '그림과 같이 "Windows PC 보호" 창이 열린다면 "추가 정보"를 클릭하면 "실행" 버튼이 보이게 됩니다. "실행" 버튼을 클릭합니다.';
	$text['그림과 같이 "사용자 계정 컨트롤" 창이 열린다면 "예"를 선택합니다.'] = '그림과 같이 "사용자 계정 컨트롤" 창이 열린다면 "예"를 선택합니다.';
	$text['프로그램 설치를 마치고, 바탕화면 바로가기나 시작 메뉴에서 IPanyVPN을 클릭하여 프로그램을 실행합니다.'] = '프로그램 설치를 마치고, 바탕화면 바로가기나 시작 메뉴에서 IPanyVPN을 클릭하여 프로그램을 실행합니다.';
	$text['통합 접속 프로그램이 열리면,'] = '통합 접속 프로그램이 열리면,';
	$text['접속아이디에 "'.$vpnid.'"을(를) 입력하고, 비밀번호를 입력하세요.'] = '접속아이디에 "'.$vpnid.'"을(를) 입력하고, 비밀번호를 입력하세요.';
	$text[$account_url.'에서 생성한 계정의 접속아이디와 비밀번호를 입력합니다.'] = $account_url.'에서 생성한 계정의 접속아이디와 비밀번호를 입력합니다.';
	$text['VPN 방식을 "IKEv2"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.'] = 'VPN 방식을 "IKEv2"로 선택하고, 접속 서버를 선택한 후 "접속하기"를 클릭하여 접속할 수 있습니다.';
	$text['VPN 방식'] = 'VPN 방식';
	$text['IKEv2 접속에 문제가 있다면, Openvpn 접속 방식을 선택하세요. (중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL을 사용하세요.)'] = 'IKEv2 접속에 문제가 있다면, Openvpn 접속 방식을 선택하세요. (중국에서는 OpenVPN 접속이 가능하지 않습니다. 대신 OpenVPN SSL을 사용하세요.)';
	$text['접속 서버'] = '접속 서버';
	$text['IPany는 다중 접속 서버를 제공합니다. 접속이 원할하지 않다면 다른 서버를 선택해 접속할 수 있습니다.'] = 'IPany는 다중 접속 서버를 제공합니다. 접속이 원할하지 않다면 다른 서버를 선택해 접속할 수 있습니다.';
	$text['접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.'] = '접속에 성공하면 "계정 관리"에서 선택한 고정아이피로 인터넷을 이용하게 됩니다.';
	$text['<span class="badge badge-danger">중국</span> 중국에서 접속 시 VPN 접속 후에도 구글 페이스북이 열리지 않는다면 DNS 서버 설정을 변경해야 합니다. 방법을 확인하려면 여기를 클릭하세요.'] = '<span class="badge badge-danger">중국</span> 중국에서 접속 시 VPN 접속 후에도 구글 페이스북이 열리지 않는다면 DNS 서버 설정을 변경해야 합니다. 방법을 확인하려면 여기를 클릭하세요.';
	$text[$osname.'에서 DNS 서버를 한국 DNS 서버로 변경하는 방법입니다.'] = $osname.'에서 DNS 서버를 한국 DNS 서버로 변경하는 방법입니다.';
	$text['윈도우 데스크톱 화면의 오른쪽 아래의 네트워크 트레이 아이콘에 마우스를 올리고 마우스 오른 쪽 버튼을 클릭합니다. <strong>네트워크 및 공유 센터 열기</strong>를 선택합니다.'] = '윈도우 데스크톱 화면의 오른쪽 아래의 네트워크 트레이 아이콘에 마우스를 올리고 마우스 오른 쪽 버튼을 클릭합니다. <strong>네트워크 및 공유 센터 열기</strong>를 선택합니다.';
	$text['PC가 인터넷에 연결된 이더넷이나 WiFi의 연결을 클릭합니다.'] = 'PC가 인터넷에 연결된 이더넷이나 WiFi의 연결을 클릭합니다.';
	$text['속성을 클릭합니다.'] = '속성을 클릭합니다.';
	$text['인터넷 프로토콜 버전4(TCP/IPv4)를 더블 클릭합니다.'] = '인터넷 프로토콜 버전4(TCP/IPv4)를 더블 클릭합니다.';
	$text['"다음 DNS 서버 주소 사용"을 선택하고 그림과 같이 DNS 서버 주소를 입력합니다.'] = '"다음 DNS 서버 주소 사용"을 선택하고 그림과 같이 DNS 서버 주소를 입력합니다.';
	$text['"확인" 및 "닫기" 버튼을 연속으로 선택하여 변경 내용을 적용합니다.  PC를 재부팅 합니다.'] = '"확인" 및 "닫기" 버튼을 연속으로 선택하여 변경 내용을 적용합니다.  PC를 재부팅 합니다.';
	$text['이 방법으로도 해결이되지 않는다면 <a href="connects_rpi_rpi.php">PI보드를 이용한 VPN 접속 방법</a>을 사용해야 합니다.'] = '이 방법으로도 해결이되지 않는다면 <a href="connects_rpi_rpi.php">PI보드를 이용한 VPN 접속 방법</a>을 사용해야 합니다.';
	$text['접속 장애 확인'] = '접속 장애 확인';
	$text['접속에 실패하면 접속 실패창이 뜨게됩니다. 여기서 접속 실패 원인을 확인할 수 있습니다.'] = '접속에 실패하면 접속 실패창이 뜨게됩니다. 여기서 접속 실패 원인을 확인할 수 있습니다.';
	$text['주요 "오류 번호"에 따른 접속 실패 원인과 해결 방법입니다.'] = '주요 "오류 번호"에 따른 접속 실패 원인과 해결 방법입니다.';
	$text['오류'] = '오류';
	$text['원인 및 해결방법'] = '원인 및 해결방법';
	$text['접속 계정의 사용자 이름, 비밀번호가 잘못되거나, 만기일이 지났거나, 이미 접속되어 있는데 다시 접속을 시도하는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. IPany.net 홈페이지의 "<a href="staticip.php">계정 관리</a>"에서 해당 계정 상태를 확인합니다.'] = '접속 계정의 사용자 이름, 비밀번호가 잘못되거나, 만기일이 지났거나, 이미 접속되어 있는데 다시 접속을 시도하는 경우입니다. IPany 서비스는 같은 계정으로 동시에 이중 접속이 되지 않습니다. IPany.net 홈페이지의 "<a href="staticip.php">계정 관리</a>"에서 해당 계정 상태를 확인합니다.';
	$text['접속 서버를 찾지 못해 발생하는 오류입니다. 인터넷 연결이 되어있지 않은 경우, DNS 오류, 방화벽으로 차단된 경우입니다. DNS 오류의 경우는 컴퓨터의 DNS 서버 설정을 "168.126.63.1"로 변경하여 해결 할 수 있습니다. 방화벽으로 차단된 경우는 다른 VPN 방식으로 접속해야 합니다.'] = '접속 서버를 찾지 못해 발생하는 오류입니다. 인터넷 연결이 되어있지 않은 경우, DNS 오류, 방화벽으로 차단된 경우입니다. DNS 오류의 경우는 컴퓨터의 DNS 서버 설정을 "168.126.63.1"로 변경하여 해결 할 수 있습니다. 방화벽으로 차단된 경우는 다른 VPN 방식으로 접속해야 합니다.';
	$text['오류87 "매개변수가 틀립니다."는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = '오류87 "매개변수가 틀립니다."는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.';
	$text['오류809는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.'] = '오류809는 Windows OS 자체의 문제 때문입니다. <a href="howto.php">문제해결 페이지</a>에 해결방법이 설명되어 있습니다.';
	$text['접속기 삭제'] = '접속기 삭제';
	$text['설정 -> 앱 (앱 및 기능)에서 프로그램을 삭제할 수 있습니다.'] = '설정 -> 앱 (앱 및 기능)에서 프로그램을 삭제할 수 있습니다.';
	$text['해외 사용자의 경우, 접속이 잘되지 않거나 인터넷 속도가 느리다면 다른 서버를 선택해 접속해 자신에게 맞는 서버를 찾아 사용합니다.'] = '해외 사용자의 경우, 접속이 잘되지 않거나 인터넷 속도가 느리다면 다른 서버를 선택해 접속해 자신에게 맞는 서버를 찾아 사용합니다.';
}
?>