<?php
if ($browserlang == "ko") {
	$text['이메일 주소로 로그인'] = '이메일 주소로 로그인';
	$text['이메일 주소를 등록하고 이메일 주소와 비밀번호로 로그인할 수 있습니다.'] = '이메일 주소를 등록하고 이메일 주소와 비밀번호로 로그인할 수 있습니다.';
	$text['비밀번호가 일치하지 않습니다. 다시 확인 후 시도해 주세요.'] = '비밀번호가 일치하지 않습니다. 다시 확인 후 시도해 주세요.';
	$text['비밀번호를 잊었다면 비밀번호를 재설정할 수 있습니다.'] = '비밀번호를 잊었다면 비밀번호를 재설정할 수 있습니다.';
	$text['비밀번호 재설정하러 가기'] = '비밀번호 재설정하러 가기';
	$text['등록되지않은 이메일 주소입니다. 다시 확인 후 시도해 주세요.'] = '등록되지않은 이메일 주소입니다. 다시 확인 후 시도해 주세요.';
	$text['이메일 주소를 성공적으로 등록했습니다. 이제 로그인할 수 있습니다.'] = '이메일 주소를 성공적으로 등록했습니다. 이제 로그인할 수 있습니다.';
	$text['이미 이메일 주소를 등록했다면 바로 로그인하세요.'] = '이미 이메일 주소를 등록했다면 바로 로그인하세요.';
	$text['이메일 주소'] = '이메일 주소';
	$text['비밀번호'] = '비밀번호';
	$text['로그인'] = '로그인';
	$text['이메일 주소를 등록하지 않았다면 지금 등록하고 로그인할 수 있습니다.'] = '이메일 주소를 등록하지 않았다면 지금 등록하고 로그인할 수 있습니다.';
	$text['이메일 주소 등록하기'] = '이메일 주소 등록하기';

	//email_register.php
	$text['이미 등록된 이메일 주소입니다.'] = '이미 등록된 이메일 주소입니다.';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = '로그인 페이지로 이동해 로그인 하세요.';
	$text['아래 주소로 이메일을 발송했습니다. 이메일을 받았는지 확인해 주세요.(스팸메일함 확인 필수)'] = '아래 주소로 이메일을 발송했습니다. 이메일을 받았는지 확인해 주세요.(스팸메일함 확인 필수)';
	$text['받은 이메일 내용의 링크를 클릭해 등록과정을 마무리하세요.'] = '받은 이메일 내용의 링크를 클릭해 등록과정을 마무리하세요.';
	$text['이메일 발송에 실패했습니다. 다시 시도해 주세요.'] = '이메일 발송에 실패했습니다. 다시 시도해 주세요.';
	$text['죄송합니다. 오류가 발생했습니다. 다시 시도해 주세요.'] = '죄송합니다. 오류가 발생했습니다. 다시 시도해 주세요.';
	$text['입력된 두개의 비밀번호가 일치하지 않습니다. 다시 입력해 주세요.'] = '입력된 두개의 비밀번호가 일치하지 않습니다. 다시 입력해 주세요.';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = '로그인 페이지로 이동해 로그인 하세요.';
	$text['이메일 로그인'] = '이메일 로그인';
	$text['이메일 주소 등록'] = '이메일 주소 등록';
	$text['이메일 등록'] = '이메일 등록';
	$text['이메일 주소를 등록하여 로그인합니다.'] = '이메일 주소를 등록하여 로그인합니다.';
	$text['로그인 용 이메일 주소 등록'] = '로그인 용 이메일 주소 등록';
	$text['등록된 이메일 주소와 비밀번호로 로그인 합니다.'] = '등록된 이메일 주소와 비밀번호로 로그인 합니다.';
	$text['이메일 주소를 입력하고 발송 버튼을 클릭하면 이메일이 발송됩니다.'] = '이메일 주소를 입력하고 발송 버튼을 클릭하면 이메일이 발송됩니다.';
	$text['받은 이메일의 링크를 클릭하여 등록과정을 마무리하세요.'] = '받은 이메일의 링크를 클릭하여 등록과정을 마무리하세요.';
	$text['본인이 사용 중이고 확인 가능한 이메일 주소를 입력해야합니다.'] = '본인이 사용 중이고 확인 가능한 이메일 주소를 입력해야합니다.';
	$text[$brand_name.' 홈페이지 로그인 시 사용할 이메일 주소입니다.'] = $brand_name.' 홈페이지 로그인 시 사용할 이메일 주소입니다.';
	$text['비밀번호 입력'] = '비밀번호 입력';
	$text['로그인에 사용할 비밀번호를 입력하세요.'] = '로그인에 사용할 비밀번호를 입력하세요.';
	$text['비밀번호 재입력'] = '비밀번호 재입력';
	$text['비밀번호를 한번 더 입력하세요.'] = '비밀번호를 한번 더 입력하세요.';
	$text['이메일 재발송'] = '이메일 재발송';
	$text['이메일 발송'] = '이메일 발송';
	$text['등록'] = '등록';
	$text['지금 다른 VPN에 접속 중이라면 VPN 접속을 끊고 이메일주소 등록을 진행해주세요.'] = '지금 다른 VPN에 접속 중이라면 VPN 접속을 끊고 이메일주소 등록을 진행해주세요.';
	$text['돌아가기'] = '돌아가기';

	//email_register_reset.php
	$text['받은 이메일 내용의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = '받은 이메일 내용의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.';
	$text['이메일 비밀번호가 변경되었습니다. 변경된 비밀번호로 로그인할 수 있습니다.'] = '이메일 비밀번호가 변경되었습니다. 변경된 비밀번호로 로그인할 수 있습니다.';
	$text['비밀번호 재설정'] = '비밀번호 재설정';
	$text['비밀번호를 잊었다면 여기서 재설정할 수 있습니다.'] = '비밀번호를 잊었다면 여기서 재설정할 수 있습니다.';
	$text['비밀번호 재설정을 위한 이메일을 발송합니다.'] = '비밀번호 재설정을 위한 이메일을 발송합니다.';
	$text['비밀번호를 재설정합니다.'] = '비밀번호를 재설정합니다.';
	$text['새로 사용할 비밀번호를 입력하세요.'] = '새로 사용할 비밀번호를 입력하세요.';
	$text['발송 버튼을 클릭하면 이메일이 발송됩니다.'] = '발송 버튼을 클릭하면 이메일이 발송됩니다.';
	$text['받은 이메일의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = '받은 이메일의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.';
	$text['이메일 주소 입력'] = '이메일 주소 입력';
	$text['변경된 비밀번호로 로그인하기.'] = '변경된 비밀번호로 로그인하기.';
	$text['비밀번호 저장'] = '비밀번호 저장';
	$text['등록이 가능하지 않은 이메일 주소입니다. 다른 이메일 주소를 사용하세요.'] = '등록이 가능하지 않은 이메일 주소입니다. 다른 이메일 주소를 사용하세요.';

	//email_pass_change.php
	$text['비밀번호 변경'] = '비밀번호 변경';
	$text['이메일 주소로 로그인에 사용하는 비밀번호를 변경합니다.'] = '이메일 주소로 로그인에 사용하는 비밀번호를 변경합니다.';
	$text['비밀번호가 변경되었습니다. 변경된 비밀번호로 다시 로그인해주세요.'] = '비밀번호가 변경되었습니다. 변경된 비밀번호로 다시 로그인해주세요.';
	$text['변경할 새 비밀번호를 입력하세요.'] = '변경할 새 비밀번호를 입력하세요.';
	$text['다시 로그인하기'] = '다시 로그인하기';
	$text['취소'] = '취소';

} elseif ($browserlang == "zh") {
	$text['이메일 주소로 로그인'] = '使用email登录';
	$text['이메일 주소를 등록하고 이메일 주소와 비밀번호로 로그인할 수 있습니다.'] = '则可以注册一个电子邮件地址，然后使用您的电子邮件地址和密码登录。';
	$text['비밀번호가 일치하지 않습니다. 다시 확인 후 시도해 주세요.'] = '密码不匹配。 请再次检查并尝试。';
	$text['비밀번호를 잊었다면 비밀번호를 재설정할 수 있습니다.'] = '如果您忘记了密码，则可以重设密码。';
	$text['비밀번호 재설정하러 가기'] = '重置密码';
	$text['등록되지않은 이메일 주소입니다. 다시 확인 후 시도해 주세요.'] = '该电子邮件地址未注册。 请再次检查并尝试。';
	$text['이메일 주소를 성공적으로 등록했습니다. 이제 로그인할 수 있습니다.'] = '您已成功注册您的电子邮件地址。 您现在可以登录。';
	$text['이미 이메일 주소를 등록했다면 바로 로그인하세요.'] = '如果您已经注册了电子邮件地址，请立即登录。';
	$text['이메일 주소'] = '电子邮件地址';
	$text['비밀번호'] = '密码';
	$text['로그인'] = '登录';
	$text['이메일 주소를 등록하지 않았다면 지금 등록하고 로그인할 수 있습니다.'] = '如果您尚未注册电子邮件地址，则可以立即注册并登录。';
	$text['이메일 주소 등록하기'] = '注册电子邮件地址';

	//email_register.php
	$text['이미 등록된 이메일 주소입니다.'] = '该邮箱地址已被注册。';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = '进入登录页面并登录。';
	$text['아래 주소로 이메일을 발송했습니다. 이메일을 받았는지 확인해 주세요.(스팸메일함 확인 필수)'] = '我们已将电子邮件发送到以下地址。 请确保您已收到电子邮件（要求检查您的垃圾邮件文件夹）。';
	$text['받은 이메일 내용의 링크를 클릭해 등록과정을 마무리하세요.'] = '单击您收到的电子邮件中的链接以完成注册过程。';
	$text['이메일 발송에 실패했습니다. 다시 시도해 주세요.'] = '电子邮件发送失败。 请再试一遍。';
	$text['죄송합니다. 오류가 발생했습니다. 다시 시도해 주세요.'] = '对不起。 发生了错误。 请再试一遍。';
	$text['입력된 두개의 비밀번호가 일치하지 않습니다. 다시 입력해 주세요.'] = '输入的两个密码不匹配。';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = '进入登录页面并登录。';
	$text['이메일 로그인'] = '使用email登录';
	$text['이메일 주소 등록'] = '电子邮件注册';
	$text['이메일 등록'] = '电子邮件注册';
	$text['이메일 주소를 등록하여 로그인합니다.'] = '注册您的电子邮件地址并登录。';
	$text['로그인 용 이메일 주소 등록'] = '注册电子邮件地址进行登录';
	$text['등록된 이메일 주소와 비밀번호로 로그인 합니다.'] = '使用您注册的电子邮件地址和密码登录。';
	$text['이메일 주소를 입력하고 발송 버튼을 클릭하면 이메일이 발송됩니다.'] = '输入您的电子邮件地址，然后单击发送按钮发送电子邮件。';
	$text['받은 이메일의 링크를 클릭하여 등록과정을 마무리하세요.'] = '单击您收到的电子邮件中的链接以完成注册过程。';
	$text['본인이 사용 중이고 확인 가능한 이메일 주소를 입력해야합니다.'] = '您必须输入您正在使用的电子邮件地址，并且可以验证。';
	$text[$brand_name.' 홈페이지 로그인 시 사용할 이메일 주소입니다.'] = '登录'.$brand_name.'主页时使用的电子邮件地址。';
	$text['비밀번호 입력'] = '密码';
	$text['로그인에 사용할 비밀번호를 입력하세요.'] = '输入密码登录。';
	$text['비밀번호 재입력'] = '重新输入密码';
	$text['비밀번호를 한번 더 입력하세요.'] = '请再次输入你的密码。';
	$text['이메일 재발송'] = '重发电子邮件';
	$text['이메일 발송'] = '邮件发送';
	$text['등록'] = '注册';
	$text['지금 다른 VPN에 접속 중이라면 VPN 접속을 끊고 이메일주소 등록을 진행해주세요.'] = '如果您当前连接到另一个 VPN，请断开 VPN 连接并注册您的电子邮件地址。';
	$text['돌아가기'] = '回到以前';

	//email_register_reset.php
	$text['받은 이메일 내용의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = '您可以通过单击收到的电子邮件中的链接来重置密码。';
	$text['이메일 비밀번호가 변경되었습니다. 변경된 비밀번호로 로그인할 수 있습니다.'] = '您的密码已被更改。 您可以使用更改后的密码登录。';
	$text['비밀번호 재설정'] = '重设密码';
	$text['비밀번호를 잊었다면 여기서 재설정할 수 있습니다.'] = '如果您忘记了密码，可以在这里重置。';
	$text['비밀번호 재설정을 위한 이메일을 발송합니다.'] = '我们将向您发送电子邮件以重置密码。';
	$text['비밀번호를 재설정합니다.'] = '重置你的密码。';
	$text['새로 사용할 비밀번호를 입력하세요.'] = '请输入新密码。';
	$text['발송 버튼을 클릭하면 이메일이 발송됩니다.'] = '单击发送按钮，将发送一封电子邮件。';
	$text['받은 이메일의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = '您可以通过单击收到的电子邮件中的链接来重置密码。';
	$text['이메일 주소 입력'] = '输入电子邮件地址';
	$text['변경된 비밀번호로 로그인하기.'] = '使用更改的密码登录';
	$text['비밀번호 저장'] = '保存密码';
	$text['등록이 가능하지 않은 이메일 주소입니다. 다른 이메일 주소를 사용하세요.'] = '此电子邮件地址不符合注册条件。 请使用其他电子邮件地址。';

	//email_pass_change.php
	$text['비밀번호 변경'] = '更改密码';
	$text['이메일 주소로 로그인에 사용하는 비밀번호를 변경합니다.'] = '更改用于使用电子邮件地址登录的密码。';
	$text['비밀번호가 변경되었습니다. 변경된 비밀번호로 다시 로그인해주세요.'] = '您的密码已被更改。 请使用更改后的密码重新登录。';
	$text['변경할 새 비밀번호를 입력하세요.'] = '输入新密码进行更改。';
	$text['다시 로그인하기'] = '重新登录';
	$text['취소'] = '取消';

	$title = $brand_name.' - 使用您的电子邮件地址登录';
	$description = '登录页面。';
} else {  //en
	$text['이메일 주소로 로그인'] = 'Sign in with email address';
	$text['이메일 주소를 등록하고 이메일 주소와 비밀번호로 로그인할 수 있습니다.'] = 'You can register an email address and sign in with your email address and password.';
	$text['비밀번호가 일치하지 않습니다. 다시 확인 후 시도해 주세요.'] = 'Passwords do not match. Please check again and try.';
	$text['비밀번호를 잊었다면 비밀번호를 재설정할 수 있습니다.'] = 'If you forgot your password, you can reset it.';
	$text['비밀번호 재설정하러 가기'] = 'Go to reset password';
	$text['등록되지않은 이메일 주소입니다. 다시 확인 후 시도해 주세요.'] = 'This email address is not registered. Please check again and try.';
	$text['이메일 주소를 성공적으로 등록했습니다. 이제 로그인할 수 있습니다.'] = 'You have successfully registered your email address. You can now sign in.';
	$text['이미 이메일 주소를 등록했다면 바로 로그인하세요.'] = 'If you have already registered an email address, you can sign in now.';
	$text['이메일 주소'] = 'Email Address';
	$text['비밀번호'] = 'Password';
	$text['로그인'] = 'Sign in';
	$text['이메일 주소를 등록하지 않았다면 지금 등록하고 로그인할 수 있습니다.'] = 'If you have not registered an email address, you can register and sign in now.';
	$text['이메일 주소 등록하기'] = 'Registering an email address';

	//email_register.php
	$text['이미 등록된 이메일 주소입니다.'] = 'This e-mail address is already registered. ';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = 'Go to the sign-in page and sign in.';
	$text['아래 주소로 이메일을 발송했습니다. 이메일을 받았는지 확인해 주세요.(스팸메일함 확인 필수)'] = 'We sent an email to the address below. Please make sure you have received the email (requires checking your spam folder).';
	$text['받은 이메일 내용의 링크를 클릭해 등록과정을 마무리하세요.'] = 'Click the link in the email you received to complete the registration process.';
	$text['이메일 발송에 실패했습니다. 다시 시도해 주세요.'] = 'Failed to send email. please try again.';
	$text['죄송합니다. 오류가 발생했습니다. 다시 시도해 주세요.'] = 'Sorry. An error has occurred. please try again.';
	$text['입력된 두개의 비밀번호가 일치하지 않습니다. 다시 입력해 주세요.'] = 'The two passwords entered do not match.';
	$text['로그인 페이지로 이동해 로그인 하세요.'] = 'Go to the sign-in page and sign in.';
	$text['이메일 로그인'] = 'Sign in wiht Email Address';
	$text['이메일 주소 등록'] = 'Register Email Address';
	$text['이메일 등록'] = 'Register Email Address';
	$text['이메일 주소를 등록하여 로그인합니다.'] = 'Sign in with Email address registered.';
	$text['로그인 용 이메일 주소 등록'] = 'Register email address for sign-in';
	$text['등록된 이메일 주소와 비밀번호로 로그인 합니다.'] = 'Sign in with your registered email address and password.';
	$text['이메일 주소를 입력하고 발송 버튼을 클릭하면 이메일이 발송됩니다.'] = 'Enter your email address and click the Send Email button to send an email.';
	$text['받은 이메일의 링크를 클릭하여 등록과정을 마무리하세요.'] = 'Click the link in the email you received to complete the registration process.';
	$text['본인이 사용 중이고 확인 가능한 이메일 주소를 입력해야합니다.'] = 'You must enter a valid email address that you are using.';
	$text[$brand_name.' 홈페이지 로그인 시 사용할 이메일 주소입니다.'] = 'Email address to use when signning in '.$brand_name.' website.';
	$text['비밀번호 입력'] = 'Password';
	$text['로그인에 사용할 비밀번호를 입력하세요.'] = 'Enter the password to sign in.';
	$text['비밀번호 재입력'] = 'Re-enter password';
	$text['비밀번호를 한번 더 입력하세요.'] = 'Please enter your password again.';
	$text['이메일 재발송'] = 'Resend email';
	$text['이메일 발송'] = 'Send Email';
	$text['등록'] = 'Registration';
	$text['지금 다른 VPN에 접속 중이라면 VPN 접속을 끊고 이메일주소 등록을 진행해주세요.'] = 'If you are currently connected to another VPN, disconnect the VPN connection and register your email address.';
	$text['돌아가기'] = 'back to previous';

	//email_register_reset.php
	$text['받은 이메일 내용의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = 'You can reset your password by clicking the link in the email you received.';
	$text['이메일 비밀번호가 변경되었습니다. 변경된 비밀번호로 로그인할 수 있습니다.'] = 'Your password has been changed. You can sign in with the changed password.';
	$text['비밀번호 재설정'] = 'Reset password';
	$text['비밀번호를 잊었다면 여기서 재설정할 수 있습니다.'] = 'If you forgot your password, you can reset it here.';
	$text['비밀번호 재설정을 위한 이메일을 발송합니다.'] = 'We will send you an email to reset your password.';
	$text['비밀번호를 재설정합니다.'] = 'Reset your password.';
	$text['새로 사용할 비밀번호를 입력하세요.'] = 'Please enter a new password.';
	$text['발송 버튼을 클릭하면 이메일이 발송됩니다.'] = 'Click Send Email button and an email will be sent. ';
	$text['받은 이메일의 링크를 클릭하여 비밀번호를 재설정할 수 있습니다.'] = 'You can reset your password by clicking the link in the email you received.';
	$text['이메일 주소 입력'] = 'Input email address';
	$text['변경된 비밀번호로 로그인하기.'] = 'Sign in with the changed password';
	$text['비밀번호 저장'] = 'Save Password';
	$text['등록이 가능하지 않은 이메일 주소입니다. 다른 이메일 주소를 사용하세요.'] = 'This email address is not eligible for registration. Please use a different email address.';

	//email_pass_change.php
	$text['비밀번호 변경'] = 'Change Password';
	$text['이메일 주소로 로그인에 사용하는 비밀번호를 변경합니다.'] = 'Change the password you use to log in with your email address.';
	$text['비밀번호가 변경되었습니다. 변경된 비밀번호로 다시 로그인해주세요.'] = 'Your password has been changed. Please log in again with the changed password.';
	$text['변경할 새 비밀번호를 입력하세요.'] = 'Enter a new password to change.';
	$text['다시 로그인하기'] = 'log in again';
	$text['취소'] = 'cancel';

	$title = $brand_name.' - Sign in with your email address';
	$description = 'Login page.';
}
?>