<?php
if ($browserlang == "ko") {
	$text['결제 내역'] = '결제 내역';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = '서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.';
	$text['주문번호'] = '주문번호';
	$text['날짜'] = '날짜';
	$text['결제자 IP'] = '결제자 IP';
	$text['추가 할인율'] = '추가 할인율';
	$text['결제 방법'] = '결제 방법';
	$text['결제 금액'] = '결제 금액';
	$text['결제자'] = '결제자';
	$text['연장 아이디(연장 개월, 단가)<br>연장전 만기일 to 연장후 만기일'] = '연장 아이디(연장 개월, 단가)<br>연장전 만기일 to 연장후 만기일';
	$text['신용카드'] = '신용카드';
	$text['매출전표 확인'] = '매출전표 확인';
	$text['거래명세표 확인'] = '거래명세표 확인';
	$text['가상계좌(입금완료)'] = '가상계좌(입금완료)';
	$text['가상계좌(입금대기)'] = '가상계좌(입금대기)';
	$text['가상계좌(미입금 취소)'] = '가상계좌(미입금 취소)';
	$text['PayPal'] = 'PayPal';
	$text['계좌이체 수동'] = '계좌이체 수동';
	$text['원'] = '원';
	$text['연장 취소'] = '연장 취소';
	$text['개월'] = '개월';
	$text['결제 내역이 없습니다.'] = '결제 내역이 없습니다.';
	$text['다시 확인'] = '다시 확인';
	$text['돌아가기'] = '돌아가기';
} elseif ($browserlang == "zh") {
	$text['결제 내역'] = '结算明细';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = '服务器连接失败。对不起。稍后再做一次吧';
	$text['주문번호'] = '订单编号';
	$text['날짜'] = '日期';
	$text['결제자 IP'] = '付款人IP';
	$text['추가 할인율'] = '附加贴现率';
	$text['결제 방법'] = '付款方法';
	$text['결제 금액'] = '支付金额';
	$text['결제자'] = '付款人';
	$text['연장 아이디(연장 개월, 단가)<br>연장전 만기일 to 연장후 만기일'] = '扩展 ID(延长月数, 单价)<br>延期前的到期日 to 延期后的到期日';
	$text['신용카드'] = '信用卡';
	$text['매출전표 확인'] = '检查销售单';
	$text['거래명세표 확인'] = '检查交易报表';
	$text['가상계좌(입금완료)'] = '虚拟账户(存款已完成)';
	$text['가상계좌(입금대기)'] = '虚拟账户(存款等待)';
	$text['가상계좌(미입금 취소)'] = '虚拟账户(因未付款而取消)';
	$text['PayPal'] = 'PayPal';
	$text['계좌이체 수동'] = '手动扩展付款（帐户转帐）';
	$text['원'] = '韩元';
	$text['연장 취소'] = '取消延期';
	$text['개월'] = '月';
	$text['결제 내역이 없습니다.'] = '没有付款记录。';
	$text['다시 확인'] = '再次确认';
	$text['돌아가기'] = '返回';

} else {  //en
	$text['결제 내역'] = 'Payment history';
	$text['서버 접속에 실패했습니다. 죄송합니다. 잠시 후 다시 접속 부탁드립니다.'] = 'Failed to connect to the server. Sorry. Please try again after a while.';
	$text['주문번호'] = '주문번호';
	$text['날짜'] = 'Date';
	$text['결제자 IP'] = 'Payer\'s IP';
	$text['추가 할인율'] = 'Additional discount rate';
	$text['결제 방법'] = 'Payment Method';
	$text['결제 금액'] = 'Amount of payment';
	$text['결제자'] = 'Payer';
	$text['연장 아이디(연장 개월, 단가)<br>연장전 만기일 to 연장후 만기일'] = 'Extended ID(number of extended months, unit price)<br>Expiration date before extension to Expiration date after extension';
	$text['신용카드'] = 'Credit card';
	$text['매출전표 확인'] = 'Check sales slip';
	$text['거래명세표 확인'] = 'Check the transaction statement';
	$text['가상계좌(입금완료)'] = 'Virtual Account(Deposit completed)';
	$text['가상계좌(입금대기)'] = 'Virtual Account(Deposit waiting)';
	$text['가상계좌(미입금 취소)'] = 'Virtual Account(Cancellation due to non-payment)';
	$text['PayPal'] = 'PayPal';
	$text['계좌이체 수동'] = 'Manual Extension Payment (Bank Transfer)';
	$text['원'] = 'KRW';
	$text['연장 취소'] = 'Cancellation of extension';
	$text['개월'] = 'month';
	$text['결제 내역이 없습니다.'] = 'There is no payment history.';
	$text['다시 확인'] = 'Check again';
	$text['돌아가기'] = 'Go back';

}

?>