<?php
if ($browserlang == "ko") {
	$text['죄송합니다. PayPal 결제는 정상적으로 되었지만 아이디 연장에 오류가 발생했습니다. 문의하기에서 연장 요청을 해주세요.'] = '죄송합니다. PayPal 결제는 정상적으로 되었지만 아이디 연장에 오류가 발생했습니다. 문의하기에서 연장 요청을 해주세요.';
	$text['죄송합니다. PayPal 결제금액이 일치하지 않습니다. 문의하기를 남겨주세요.'] = '죄송합니다. PayPal 결제금액이 일치하지 않습니다. 문의하기를 남겨주세요.';
	$text['죄송합니다. PayPal 결제에 문제가 발생했습니다. 문의하기를 남겨주세요.'] = '죄송합니다. PayPal 결제에 문제가 발생했습니다. 문의하기를 남겨주세요.';
	$text['아래 PayPal 결제 진행 버튼을 클릭하면 결제가 진행됩니다.<br>PayPal 결제가 완료되면 사용 기간이 자동으로 연장됩니다.'] = '아래 PayPal 결제 진행 버튼을 클릭하면 결제가 진행됩니다.<br>PayPal 결제가 완료되면 사용 기간이 자동으로 연장됩니다.';
	$text['연장 신청 내역'] = '연장 신청 내역';
	$text['아이디'] = '아이디';
	$text['연장 개월수'] = '연장 개월수';
	$text['월단가'] = '월단가';
	$text['사용료'] = '사용료';
	$text['개월'] = '개월';
	$text['원'] = '원';
	$text['PayPal 결제는 US 달러로만 결제됩니다.'] = 'PayPal 결제는 US 달러로만 결제됩니다.';
	$text['반드시 아래 PayPal 버튼을 클릭하여 결제를 진행해야만 결제 확인이 가능합니다.'] = '반드시 아래 PayPal 버튼을 클릭하여 결제를 진행해야만 결제 확인이 가능합니다.';
	$text['여러개 아이디를 연장해야한다면 모두 선택해 한번에 결제하세요. PayPal 수수료를 절약할 수 있습니다.'] = '여러개 아이디를 연장해야한다면 모두 선택해 한번에 결제하세요. PayPal 수수료를 절약할 수 있습니다.';
	$text['원화'] = '원화';
	$text['US 달러'] = 'US 달러';
	$text['결제할 금액'] = '결제할 금액';
	$text['PayPal 수수료 포함'] = 'PayPal 수수료 포함';
	$text['PayPal 계정이 없어도 카드로 결제 가능합니다.'] = 'PayPal 계정이 없어도 카드로 결제 가능합니다.';
	$text['<span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f"> 직불카드 또는 신용카드</span>를 클릭하세요.'] = '<span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f"> 직불카드 또는 신용카드</span>를 클릭하세요.';
	$text['취소'] = '취소';
	$text['PayPal로 부터 결제 진행 요청을 받았습니다.\n결제 확인과 사용기간 연장을 진행합니다.'] = 'PayPal로 부터 결제 진행 요청을 받았습니다.\n결제 확인과 사용기간 연장을 진행합니다.';

} elseif ($browserlang == "zh") {
	$text['죄송합니다. PayPal 결제는 정상적으로 되었지만 아이디 연장에 오류가 발생했습니다. 문의하기에서 연장 요청을 해주세요.'] = '对不起。 PayPal付款成功，但是ID扩展名发生错误。 请在“联系我们”页面上提出扩展请求。';
	$text['죄송합니다. PayPal 결제금액이 일치하지 않습니다. 문의하기를 남겨주세요.'] = '对不起。 PayPal付款不匹配。 请在“联系我们”页面上进行询问。';
	$text['죄송합니다. PayPal 결제에 문제가 발생했습니다. 문의하기를 남겨주세요.'] = '对不起。 您的PayPal付款有问题。 请留下询问。';
	$text['아래 PayPal 결제 진행 버튼을 클릭하면 결제가 진행됩니다.<br>PayPal 결제가 완료되면 사용 기간이 자동으로 연장됩니다.'] = '单击下面的PayPal付款按钮以继续付款。<br>完成PayPal付款后，订阅期将自动延长。';
	$text['연장 신청 내역'] = '延期申请详情';
	$text['아이디'] = 'ID';
	$text['연장 개월수'] = '延长月份';
	$text['월단가'] = '每月价格';
	$text['사용료'] = '聘请';
	$text['개월'] = '月';
	$text['원'] = '韩元';
	$text['PayPal 결제는 US 달러로만 결제됩니다.'] = 'PayPal付款仅以美元支付。';
	$text['반드시 아래 PayPal 버튼을 클릭하여 결제를 진행해야만 결제 확인이 가능합니다.'] = '必须通过单击下面的PayPal按钮进行付款以确认付款。';
	$text['여러개 아이디를 연장해야한다면 모두 선택해 한번에 결제하세요. PayPal 수수료를 절약할 수 있습니다.'] = '如果您需要扩展多个ID，请全部选中并立即付款。 节省PayPal费用。';
	$text['원화'] = '韩元';
	$text['US 달러'] = 'USD';
	$text['결제할 금액'] = '该付的钱';
	$text['PayPal 수수료 포함'] = '包括PayPal费用';
	$text['PayPal 계정이 없어도 카드로 결제 가능합니다.'] = '即使您没有PayPal帐户，也可以通过卡付款。';
	$text['<span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f"> 직불카드 또는 신용카드</span>를 클릭하세요.'] = '点击<span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f"> 借记卡或信用卡</span>。';
	$text['취소'] = '取消';
	$text['PayPal로 부터 결제 진행 요청을 받았습니다.\n결제 확인과 사용기간 연장을 진행합니다.'] = '我们收到了来自PayPal的付款请求。\n请检查付款并延长使用期限。';


} else {  //en
	$text['죄송합니다. PayPal 결제는 정상적으로 되었지만 아이디 연장에 오류가 발생했습니다. 문의하기에서 연장 요청을 해주세요.'] = 'Sorry. PayPal payment was successful, but an error occurred in the ID extension. Please make an extension request on the Contact Us page.';
	$text['죄송합니다. PayPal 결제금액이 일치하지 않습니다. 문의하기를 남겨주세요.'] = 'Sorry. PayPal payments do not match. Please leave an inquiry on the Contact Us page.';
	$text['죄송합니다. PayPal 결제에 문제가 발생했습니다. 문의하기를 남겨주세요.'] = 'Sorry. There was a problem with your PayPal payment. Please leave an inquiry.';
	$text['아래 PayPal 결제 진행 버튼을 클릭하면 결제가 진행됩니다.<br>PayPal 결제가 완료되면 사용 기간이 자동으로 연장됩니다.'] = 'Click the PayPal payment button below to proceed with payment.<br>When PayPal payment is completed, the subscription period is automatically extended.';
	$text['연장 신청 내역'] = 'Details of application for extension';
	$text['아이디'] = 'ID';
	$text['연장 개월수'] = 'Extension months';
	$text['월단가'] = 'Monthly price';
	$text['사용료'] = 'Fee';
	$text['개월'] = 'months';
	$text['원'] = 'KRW';
	$text['PayPal 결제는 US 달러로만 결제됩니다.'] = 'PayPal payments are only made in US dollars.';
	$text['반드시 아래 PayPal 버튼을 클릭하여 결제를 진행해야만 결제 확인이 가능합니다.'] = 'Payment must be made by clicking the PayPal button below to confirm payment.';
	$text['여러개 아이디를 연장해야한다면 모두 선택해 한번에 결제하세요. PayPal 수수료를 절약할 수 있습니다.'] = 'If you need to extend multiple IDs, select them all and pay at once. Then you will save PayPal fees.';
	$text['원화'] = 'KRW';
	$text['US 달러'] = 'USD';
	$text['결제할 금액'] = 'Amount to be paid';
	$text['PayPal 수수료 포함'] = 'PayPal fees included';
	$text['PayPal 계정이 없어도 카드로 결제 가능합니다.'] = 'You can pay by card even if you do not have a PayPal account.';
	$text['<span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f"> 직불카드 또는 신용카드</span>를 클릭하세요.'] = 'Click on <span class="badge py-2 px-4" style="background-color:#e1e7eb; color:#2c2e2f">Debit or Credit Card</span>';
	$text['취소'] = 'Cancel';
	$text['PayPal로 부터 결제 진행 요청을 받았습니다.\n결제 확인과 사용기간 연장을 진행합니다.'] = 'We received a payment request from PayPal.\nCheck payment and extend the usage period.';


}

?>