<?php

if ($browserlang == "en") {
	$text['이용 요금'] = 'Usage fee';
	$text[$brand_name.'은 사용량 제한 없이 월 정액으로 이용할 수 있습니다.'] = 'IPany can be used on a monthly basis with no usage limit.';
	$text['저렴하게는 월 8천원에 이용 가능하며. 많이 사용한다면 거기서 더 할인이 가능합니다.'] = 'It is available at a low price of 8,000 KRW per month. If you use more, you can get more discounts there.';
} elseif ($browserlang == "zh") {
	$text['이용 요금'] = '使用费';
	$text[$brand_name.'은 사용량 제한 없이 월 정액으로 이용할 수 있습니다.'] = 'IPany可以每月使用，没有使用限制。';
	$text['저렴하게는 월 8천원에 이용 가능하며. 많이 사용한다면 거기서 더 할인이 가능합니다.'] = '它的价格低至每月8,000韩元。 如果您使用更多，则可以在那里获得更多折扣。';
} else {
	$text['이용 요금'] = '이용 요금';
	$text[$brand_name.'은 사용량 제한 없이 월 정액으로 이용할 수 있습니다.'] = $brand_name.'은 사용량 제한 없이 월 정액으로 이용할 수 있습니다.';
	$text['저렴하게는 월 8천원에 이용 가능하며. 많이 사용한다면 거기서 더 할인이 가능합니다.'] = '저렴하게는 월 8천원에 이용 가능하며. 많이 사용한다면 거기서 더 할인이 가능합니다.';
}

?>