<?php
if ($browserlang == "en") {
	$text['Google로 로그인'] = 'Sign in with Google';
	$text['Facebook 로그인'] = 'Sign in with Facebook';
	$text['Naver로 로그인'] = 'Sign in with Naver';
	$text['Kakao로 로그인'] = 'Sign in with Kakao';
	$text['이메일 주소로 로그인하기'] = 'Sign in with email address';
	$text['VPN 접속 계정 관리'] = 'VPN account management';
	$text[$brand_name.'은 VPN 접속에 사용되는 아이디와 비밀번호를 사용자가 직접 만들고 관리합니다.'] = 'In '.$brand_name.' users create and manage IDs and passwords used for VPN connections.';
	$text['처음으로 생성한 VPN 접속 아이디로 3일간 무료로 사용할 수 있습니다.'] = 'You can use it free for 3 days with the first VPN connection ID you created.';
	$text['가입이 필요하지 않습니다.'] = 'No subscription required.';
	$text['아래 SNS 계정 중 하나를 선택해 로그인하세요.'] = 'Select one of the social media accounts below to sign in.';
	$text['SNS 계정으로 로그인하면 VPN 접속에 필요한 아이디를 자신이 직접 만들고 관리할 수 있습니다.'] = 'If you sign in with your SNS account, you can create and manage your own ID required for VPN access.';
	$text['20일 무료 연장 이벤트를 진행합니다.'] = 'We are holding a 20-day free extension event.';
	$text[$brand_name.' <strong>사용기를 자신의 블로그나 인터넷 카페</strong>에 올려 주시면 20일 무료 사용기간을 드립니다.'] = 'If you post a testimonial on your blog or internet cafe, we will give you a 20-day free trial period.';
	$text['올리신 글의 링크를 보내주시면 사용 중인 VPN 접속 아이디를 20일 연장해 드립니다. '.$brand_name.' 홈페이지 "문의하기"에 링크를 남겨주세요.'] = 'If you send us the link of the post you posted, we will extend the VPN connection ID you are using for 20 days. Please leave that link on the IPany homepage "Contact Us".';
	$text['많은 참여 부탁 드립니다. 감사합니다.'] = 'We look forward to your participation. Thank you.';
	$text['(이 이벤트는 한시적으로 진행되며, 이벤트가 종료되면 이 게시물은 사라지게 됩니다.)'] = 'This event is on a temporary basis, and this post will disappear when the event is over.';
	$text['서버 장애 공지'] = 'Service failure notice';
	$text['장애내용'] = '';
	$text['지금 복구 작업 중이니 잠시만 기다려 주시기 바랍니다.'] = 'We are working on a recovery right now, so please wait a moment.';
	$text['불편을 드려 대단히 죄송합니다.'] = 'We are very sorry for the inconvenience.';
	$text['로그인 버튼이 동작하지 않는다면 F5키를 눌러 페이지를 리로드하세요.'] = 'If the sign-in button doesn\'t work, press F5 to reload the page.';
	$text['구글과 페이스북 연결이 차단된 중국 사용자라면 네이버나 이메일 주소로 로그인하세요.'] = 'If you are a Chinese user whose connection to Google and Facebook is blocked, sign in with Naver or your email address.';
	$text['구글 로그인이 동작하지 않으면 크롬 브라우저를 이용하세요.'] = 'If Google sign-in does not work, use Chrome browser.';
	$text['SNS 로그인이 가능하지 않다면 Email 주소를 등록하여 로그인할 수 있습니다.'] = 'If SNS sign-in is not possible, you can sign in by registering an email address.';

	$title = $brand_name.' Sign-in';
	$description = 'Sign in with your SNS account without registering as a member.';
} elseif ($browserlang == "zh") {
	$text['Google로 로그인'] = '使用Google登录';
	$text['Facebook 로그인'] = '使用Facebook登录';
	$text['Naver로 로그인'] = '使用Naver登录';
	$text['Kakao로 로그인'] = '使用Kakao登录';
	$text['이메일 주소로 로그인하기'] = '使用Email登录';
	$text['VPN 접속 계정 관리'] = 'VPN访问帐户管理';
	$text[$brand_name.'은 VPN 접속에 사용되는 아이디와 비밀번호를 사용자가 직접 만들고 관리합니다.'] = '在'.$brand_name.'中，用户创建和管理用于VPN访问的ID和密码。';
	$text['처음으로 생성한 VPN 접속 아이디로 3일간 무료로 사용할 수 있습니다.'] = '您可以使用创建的第一个VPN连接ID免费使用3天。';
	$text['가입이 필요하지 않습니다.'] = '无需订阅。';
	$text['아래 SNS 계정 중 하나를 선택해 로그인하세요.'] = '在下面选择一个社交媒体帐户登录。';
	$text['SNS 계정으로 로그인하면 VPN 접속에 필요한 아이디를 자신이 직접 만들고 관리할 수 있습니다.'] = '如果使用SNS帐户登录，则可以创建和管理VPN访问所需的自己的ID。';
	$text['20일 무료 연장 이벤트를 진행합니다.'] = '我们正在举行为期20天的免费扩展活动。';
	$text[$brand_name.' <strong>사용기를 자신의 블로그나 인터넷 카페</strong>에 올려 주시면 20일 무료 사용기간을 드립니다.'] = '如果您在博客或网吧上发布推荐，我们将为您提供20天的免费试用期。';
	$text['올리신 글의 링크를 보내주시면 사용 중인 VPN 접속 아이디를 20일 연장해 드립니다. '.$brand_name.' 홈페이지 "문의하기"에 링크를 남겨주세요.'] = '如果您将您发布的帖子的链接发送给我们，我们会将您使用的VPN连接ID延长20天。 请将该链接留在IPany主页"联系我们"上。';
	$text['많은 참여 부탁 드립니다. 감사합니다.'] = '我们非常期待你的参与。 谢谢你。';
	$text['(이 이벤트는 한시적으로 진행되며, 이벤트가 종료되면 이 게시물은 사라지게 됩니다.)'] = '该事件是暂时的，此事件结束后，该信息将消失。';
	$text['서버 장애 공지'] = '服务失败通知';
	$text['장애내용'] = '';
	$text['지금 복구 작업 중이니 잠시만 기다려 주시기 바랍니다.'] = '我们正在努力进行恢复，因此请稍等。';
	$text['불편을 드려 대단히 죄송합니다.'] = '不便之处，敬请原谅。';
	$text['로그인 버튼이 동작하지 않는다면 F5키를 눌러 페이지를 리로드하세요.'] = '如果登录按钮不起作用，请按F5重新加载页面。';
	$text['구글과 페이스북 연결이 차단된 중국 사용자라면 네이버나 이메일 주소로 로그인하세요.'] = '如果您是中国用户，并且与Google和Facebook的连接被阻止，请使用Naver或您的电子邮件地址登录。';
	$text['구글 로그인이 동작하지 않으면 크롬 브라우저를 이용하세요.'] = '如果Google登录不起作用，请使用Chrome浏览器。';
	$text['SNS 로그인이 가능하지 않다면 Email 주소를 등록하여 로그인할 수 있습니다.'] = '如果无法登录SNS，则可以通过注册电子邮件地址登录。';

	$title = $brand_name.' 登入';
	$description = '使用您的SNS帐户登录而无需注册成为会员。';
} else {
	$text['Google로 로그인'] = 'Google로 로그인';
	$text['Facebook 로그인'] = 'Facebook 로그인';
	$text['Naver로 로그인'] = 'Naver로 로그인';
	$text['Kakao로 로그인'] = 'Kakao로 로그인';
	$text['이메일 주소로 로그인하기'] = '이메일 주소로 로그인하기';
	$text['VPN 접속 계정 관리'] = 'VPN 접속 계정 관리';
	$text[$brand_name.'은 VPN 접속에 사용되는 아이디와 비밀번호를 사용자가 직접 만들고 관리합니다.'] = $brand_name.'은 VPN 접속에 사용되는 아이디와 비밀번호를 사용자가 직접 만들고 관리합니다.';
	$text['처음으로 생성한 VPN 접속 아이디로 3일간 무료로 사용할 수 있습니다.'] = '처음으로 생성한 VPN 접속 아이디로 3일간 무료로 사용할 수 있습니다.';
	$text['가입이 필요하지 않습니다.'] = '가입이 필요하지 않습니다.';
	$text['아래 SNS 계정 중 하나를 선택해 로그인하세요.'] = '아래 SNS 계정 중 하나를 선택해 로그인하세요.';
	$text['SNS 계정으로 로그인하면 VPN 접속에 필요한 아이디를 자신이 직접 만들고 관리할 수 있습니다.'] = 'SNS 계정으로 로그인하면 VPN 접속에 필요한 아이디를 자신이 직접 만들고 관리할 수 있습니다.';
	$text['20일 무료 연장 이벤트를 진행합니다.'] = '20일 무료 연장 이벤트를 진행합니다.';
	$text[$brand_name.' <strong>사용기를 자신의 블로그나 인터넷 카페</strong>에 올려 주시면 20일 무료 사용기간을 드립니다.'] = $brand_name.' <strong>사용기를 자신의 블로그나 인터넷 카페</strong>에 올려 주시면 20일 무료 사용기간을 드립니다.';
	$text['올리신 글의 링크를 보내주시면 사용 중인 VPN 접속 아이디를 20일 연장해 드립니다. '.$brand_name.' 홈페이지 "문의하기"에 링크를 남겨주세요.'] = '올리신 글의 링크를 보내주시면 사용 중인 VPN 접속 아이디를 20일 연장해 드립니다. '.$brand_name.' 홈페이지 "문의하기"에 링크를 남겨주세요.';
	$text['많은 참여 부탁 드립니다. 감사합니다.'] = '많은 참여 부탁 드립니다. 감사합니다.';
	$text['(이 이벤트는 한시적으로 진행되며, 이벤트가 종료되면 이 게시물은 사라지게 됩니다.)'] = '(이 이벤트는 한시적으로 진행되며, 이벤트가 종료되면 이 게시물은 사라지게 됩니다.)';
	$text['서버 장애 공지'] = '서버 장애 공지';
	$text['장애내용'] = 'DB 서버 이상으로 VPN 접속과 홈페이지 로그인이 되지 않고 있습니다.';
	$text['지금 복구 작업 중이니 잠시만 기다려 주시기 바랍니다.'] = '지금 복구 작업 중이니 잠시만 기다려 주시기 바랍니다.';
	$text['불편을 드려 대단히 죄송합니다.'] = '불편을 드려 대단히 죄송합니다.';
	$text['로그인 버튼이 동작하지 않는다면 F5키를 눌러 페이지를 리로드하세요.'] = '로그인 버튼이 동작하지 않는다면 F5키를 눌러 페이지를 리로드하세요.';
	$text['구글과 페이스북 연결이 차단된 중국 사용자라면 네이버나 이메일 주소로 로그인하세요.'] = '구글과 페이스북 연결이 차단된 중국 사용자라면 네이버나 이메일 주소로 로그인하세요.';
	$text['구글 로그인이 동작하지 않으면 크롬 브라우저를 이용하세요.'] = '구글 로그인이 동작하지 않으면 크롬 브라우저를 이용하세요.';
	$text['SNS 로그인이 가능하지 않다면 Email 주소를 등록하여 로그인할 수 있습니다.'] = 'SNS 로그인이 가능하지 않다면 Email 주소를 등록하여 로그인할 수 있습니다.';


}
?>